// English log sentences -- the reference table.
//
// `LogCatalogue` is `typeof` this object, so this file is the list: a
// translation may only answer keys that appear here, and `logStringsFor` fills
// its gaps from here. See `src/logs.ts` for the registry and the rules.
//
// Keep sentences short: every one is written to the log file verbatim, and the
// `event` id already says what happened. Explanations belong in comments here.

var LogsEn = {
  [Log.Run.Start]: '[TsumTsum] Start',
  [Log.Run.StartBusy]: '[TsumTsum] Previous run still stopping; not starting',
  [Log.Run.Stop]: '[TsumTsum] Stop',
  [Log.Run.StopSlow]: '[TsumTsum] Task loop still running; letting it finish',
  [Log.Task.LoopStopped]: 'TaskController Stop',
  [Log.Board.Recognized]: 'Recognized Tsums',
  [Log.Board.RecognitionStart]: 'Start Tsums recognition',
  [Log.Board.RecognitionTime]: 'Tsums recognised',
  [Log.Board.PathStart]: 'Start path calculation',
  [Log.Board.PathDone]: 'Calculated path',
  [Log.Board.LinkReach]: 'Link reach',
  [Log.Board.DeadScan]: 'Chain drawn but tsums still standing',
  [Log.Board.Stalled]: 'Board not taking chains; fanning',
  [Log.Bubble.Cleared]: 'Clear bubbles',
  [Log.Bubble.Generated]: 'Bubble generated',
  [Log.Skill.Use]: 'Use skill',
  [Log.Skill.ReadyAgain]: 'Skill full again; sweeping bubbles and repeating',
  [Log.Skill.TiaraNoDream]: '[Tiara] No thought bubble',
  [Log.Skill.TiaraDimDream]: '[Tiara] Bubble gone before read',
  [Log.Skill.TiaraBusy]: '[Tiara] Board still moving, firing anyway',
  [Log.Skill.TiaraDream]: '[Tiara] Bubble shows',
  [Log.Skill.TiaraPicked]: '[Tiara] Tapped',
  [Log.Skill.TiaraUnsure]: '[Tiara] No confident match, stopping',
  [Log.Skill.FormalBeastModeStart]: '[Formal Beast] Twin gauge up; levelling halves',
  [Log.Skill.FormalBeastModeEnd]: '[Formal Beast] Twin gauge gone',
  [Log.Skill.ElsaDone]: '[Coronation Elsa] Freeze window closed',
  [Log.Skill.ElsaRoundOver]: '[Coronation Elsa] Round ended inside the window',
  [Log.Skill.ElsaLegacyDone]: '[Coronation Elsa Legacy] Freeze window closed',
  [Log.Skill.GastonDone]: '[Gaston] Window closed',
  [Log.Skill.GastonPass]: '[Gaston] Chain drawn',
  [Log.Skill.RapunzelDone]: '[Rapunzel+] Mixed-colour chain drawn',
  [Log.Skill.LorcanaAuroraDone]: '[Lorcana Aurora] Bubble chain drawn',
  [Log.Skill.LorcanaAuroraNoChain]: '[Lorcana Aurora] No bubbles to chain; skill wasted',
  [Log.Skill.LorcanaAuroraStayed]: '[Lorcana Aurora] Bubbles stayed; chain not taken',
  [Log.Skill.LorcanaAuroraSwept]: '[Lorcana Aurora] Bubbles popped in place',
  [Log.Play.GameStart]: 'Game Start',
  [Log.Play.GamingFast]: 'Playing',
  [Log.Play.GameOver]: 'Game Over',
  [Log.Play.ConfirmingGameOver]: 'Unknown screen; confirming game over',
  [Log.Play.CheckBonusItems]: 'Check bonus items',
  [Log.Play.RoundDelayStarted]: 'Waiting before the next round',
  [Log.Play.RoundDelayOver]: 'Wait over; next round',
  [Log.Play.RoundDelaySkipped]: 'Wait cut short; next round',
  [Log.Play.RoundTimeUp]: 'Round hit Max Round Duration',
  [Log.Play.RoundCoastGaveUp]: 'Round never ended; handing back',
  [Log.Tsums.Detected]: 'MyTsum read from the settings page',
  [Log.Tsums.Identified]: 'MyTsum identified',
  [Log.Tsums.Unidentified]: 'Selected tsum unknown; round recorded without one',
  [Log.Tsums.Unreadable]: 'Pre-round tsum icon unreadable',
  [Log.Tsums.NoLibrary]: 'Tsum library missing; rounds recorded without a tsum',
  [Log.Tsums.StaleTemplate]: 'Tsum library mismatches this release; ignored',
  [Log.Tsums.NoBoardColors]: 'No board colours in tsum library; sampling skill button',
  [Log.Lorcana.Transformed]: '[Lorcana] Transformed',
  [Log.Lorcana.Untransformed]: '[Lorcana] Gauge ring back; not transformed',
  [Log.Fever.Start]: '[Fever] Fever time',
  [Log.Fever.End]: '[Fever] Fever over',
  [Log.Screen.Detect]: 'Detecting screen',
  [Log.Screen.CalculateSize]: 'Calculating screen size',
  [Log.Screen.Offset]: 'Screen offset and size',
  [Log.App.Start]: 'Start TsumTsum app',
  [Log.Page.Current]: 'Current page',
  [Log.Page.Friends]: 'Friends page',
  [Log.Page.Tsums]: 'Tsum collection page',
  [Log.Gifts.ReceiveAll]: 'Receive all gifts',
  [Log.Gifts.ReceiveOneByOne]: 'Receive gift one by one',
  [Log.Gifts.ReceiveAgain]: 'Receive gift again',
  [Log.Gifts.AllReceived]: 'All gifts received',
  [Log.Gifts.Completed]: 'Receiving gifts completed',
  [Log.Gifts.CheckUnreceived]: 'Check unreceived gift',
  [Log.Gifts.ReceiveOneMedalsOnly]: 'Only medals left in mailbox',
  [Log.Hearts.ReadRecords]: 'Reading records',
  [Log.Hearts.SaveRecords]: 'Saving records',
  [Log.Hearts.SendStart]: 'Start sending hearts',
  [Log.Hearts.SendDone]: 'Finished sending hearts',
  [Log.Hearts.Screenful]: 'Hearts sent from this page',
  [Log.Hearts.ListEnd]: 'End of ranking',
  [Log.Hearts.ZeroScore]: 'Reached friends with no score',
  [Log.Hearts.TimeUp]: 'Time\'s up',
  [Log.Report.Saved]: 'Report saved',
  [Log.Report.Failed]: 'Report not saved',
  [Log.Walk.Start]: 'Walkthrough recording: drive the game yourself',
  [Log.Walk.Page]: 'Screen recorded',
  [Log.Walk.Tap]: 'Tap recorded',
  [Log.Walk.Done]: 'Walkthrough recorded',
  [Log.Unlock.NowQueued]: 'Raising level caps next loop turn',
  [Log.Unlock.NowRefused]: 'Not raising level caps now',
  [Log.Unlock.NowWaiting]: 'Round in progress; raising level caps after',
  [Log.Unlock.NowYielded]: 'Yielding to level-cap sweep',
  [Log.Unlock.Start]: 'Looking for capped Tsums',
  [Log.Unlock.Raised]: 'Raised a Tsum\'s level cap',
  [Log.Unlock.NextPage]: 'All eight capped; next collection page',
  [Log.Unlock.SortFailed]: 'Could not re-sort the collection',
  [Log.Unlock.SortRestored]: 'Collection order restored',
  [Log.Unlock.RaiseNotConfirmed]: 'Level cap not raised; out of coins?',
  [Log.Unlock.Retrying]: 'Raise failed; retaking collection page',
  [Log.Unlock.End]: 'Level-cap raising done',
  [Log.Box.NowQueued]: 'Buying boxes next loop turn',
  [Log.Box.NowRefused]: 'Not buying boxes now',
  [Log.Box.NowWaiting]: 'Round in progress; buying boxes after',
  [Log.Box.Start]: 'Going to the store for boxes',
  [Log.Box.StoreLoading]: 'Store boxes did not load',
  [Log.Box.NotOffered]: 'Box not on sale today',
  [Log.Box.TabNotTaken]: 'Store would not open that box',
  [Log.Box.Buying]: 'Buying a box',
  [Log.Box.Bought]: 'Bought a box',
  [Log.Box.SoldOut]: 'Box sold out',
  [Log.Box.NoCoins]: 'Not enough Coins; cancelled, no Rubies spent',
  [Log.Box.TenRefused]: 'Store refused a 10-Time purchase; box almost sold out',
  [Log.Box.ToastStuck]: '10-Time refusal would not close',
  [Log.Box.DialogMissing]: 'Purchase confirmation missing',
  [Log.Box.Retrying]: 'Purchase failed; retaking store page',
  [Log.Box.RevealsStuck]: 'Box reveals stuck',
  [Log.Box.PurchaseLimit]: 'Purchase limit reached',
  [Log.Box.End]: 'Box buying done'
}

logRegisterStrings(Locale.English, LogsEn);
