// Traditional Chinese (Taiwan) log sentences.
//
// `LogCataloguePartial`, so it may omit a key: `logStringsFor` fills the gap
// from `src/logsEn.ts`, which is what lets a new event ship a sentence before it
// has been translated. `npm run i18n:check` lists what is still missing.
// Keep sentences short, as in the English table.

var LogsZhTw: LogCataloguePartial = {
  [Log.Run.Start]: '[TsumTsum] 啟動',
  [Log.Run.StartBusy]: '[TsumTsum] 上次執行尚未停止，不重複啟動',
  [Log.Run.Stop]: '[TsumTsum] 停止',
  [Log.Run.StopSlow]: '[TsumTsum] 任務迴圈尚未結束，等待中',
  [Log.Task.LoopStopped]: 'TaskController 停止',
  [Log.Task.StoodAside]: '本局進行中，例行工作先讓開',
  [Log.Board.Recognized]: '成功辨識 Tsums',
  [Log.Board.RecognitionStart]: '開始辨識 Tsums',
  [Log.Board.RecognitionTime]: 'Tsums 辨識完成',
  [Log.Board.PathStart]: '開始計算路徑',
  [Log.Board.PathDone]: '成功計算路徑',
  [Log.Board.LinkReach]: '連線距離',
  [Log.Board.DeadScan]: '已連線但 Tsum 仍在原位',
  [Log.Board.Stalled]: '盤面無法連線，改用風扇',
  [Log.Bubble.Cleared]: '清除泡泡',
  [Log.Bubble.Generated]: '產生泡泡',
  [Log.Skill.Use]: '使用技能',
  [Log.Skill.ReadyAgain]: '技能再次集滿，清泡泡後再發動',
  [Log.Skill.TiaraNoDream]: '[皇冠米妮] 沒有想像泡泡',
  [Log.Skill.TiaraDimDream]: '[皇冠米妮] 泡泡讀取前已消失',
  [Log.Skill.TiaraBusy]: '[皇冠米妮] 畫面仍在變動，仍然發動',
  [Log.Skill.TiaraDream]: '[皇冠米妮] 泡泡顯示',
  [Log.Skill.TiaraPicked]: '[皇冠米妮] 點擊',
  [Log.Skill.TiaraUnsure]: '[皇冠米妮] 沒有禮物符合，停止',
  [Log.Skill.FormalBeastModeStart]: '[禮服野獸] 雙量表出現，維持平衡',
  [Log.Skill.FormalBeastModeEnd]: '[禮服野獸] 雙量表結束',
  [Log.Skill.ElsaDone]: '[加冕日艾莎] 冰凍時間結束',
  [Log.Skill.ElsaRoundOver]: '[加冕日艾莎] 回合在冰凍時間內結束',
  [Log.Skill.ElsaLegacyDone]: '[加冕日艾莎 舊版] 冰凍時間結束',
  [Log.Skill.GastonDone]: '[加斯頓] 時間結束',
  [Log.Skill.GastonPass]: '[加斯頓] 已連線',
  [Log.Skill.RapunzelDone]: '[樂佩+] 已連出混色連線',
  [Log.Skill.LorcanaAuroraDone]: '[Lorcana 奧蘿拉] 已連出泡泡連線',
  [Log.Skill.LorcanaAuroraNoChain]: '[Lorcana 奧蘿拉] 沒有泡泡可連，技能浪費',
  [Log.Skill.LorcanaAuroraStayed]: '[Lorcana 奧蘿拉] 泡泡還在，連線未被接受',
  [Log.Skill.LorcanaAuroraSwept]: '[Lorcana 奧蘿拉] 已就地點破泡泡',
  [Log.Play.GameStart]: '遊戲開始',
  [Log.Play.GamingFast]: '遊戲中',
  [Log.Play.GameOver]: '遊戲結束',
  [Log.Play.ConfirmingGameOver]: '畫面無法辨識，確認是否結束',
  [Log.Play.CheckBonusItems]: '檢查道具',
  [Log.Play.RoundDelayStarted]: '下一局前先休息',
  [Log.Play.RoundDelayOver]: '休息結束，下一局',
  [Log.Play.RoundDelaySkipped]: '休息略過，下一局',
  [Log.Play.RoundTimeUp]: '已達單局時間上限',
  [Log.Play.RoundCoastGaveUp]: '本局未結束，交回排程',
  [Log.Tsums.Detected]: '從設定頁讀取使用中的 Tsum',
  [Log.Tsums.Identified]: '使用中的 Tsum',
  [Log.Tsums.Unidentified]: '無法辨識 Tsum，本局不記錄',
  [Log.Tsums.Unreadable]: '無法讀取開始畫面的 Tsum 圖示',
  [Log.Tsums.NoLibrary]: '無法載入 Tsum 樣板，不記錄 Tsum',
  [Log.Tsums.StaleTemplate]: 'Tsum 樣板版本不符，已略過',
  [Log.Tsums.NoBoardColors]: '樣板無盤面顏色，改讀技能按鈕',
  [Log.Lorcana.Transformed]: '[Lorcana] 已變身',
  [Log.Lorcana.Untransformed]: '[Lorcana] 變身環又出現，尚未變身',
  [Log.Fever.Start]: '[Fever] Fever 時間',
  [Log.Fever.End]: '[Fever] Fever 結束',
  [Log.Screen.Detect]: '偵測畫面',
  [Log.Screen.CalculateSize]: '計算螢幕大小',
  [Log.Screen.Offset]: '畫面位移與大小',
  [Log.App.Start]: '啟動 TsumTsum 應用程式',
  [Log.Page.Current]: '目前頁面',
  [Log.Page.Friends]: '朋友頁面',
  [Log.Page.Tsums]: 'Tsum 收集頁面',
  [Log.Gifts.ReceiveAll]: '接收所有禮物',
  [Log.Gifts.ReceiveOneByOne]: '一個一個接收禮物',
  [Log.Gifts.ReceiveAgain]: '再接收禮物一次',
  [Log.Gifts.AllReceived]: '已接收所有禮物',
  [Log.Gifts.Completed]: '完成接收禮物',
  [Log.Gifts.CheckUnreceived]: '檢查未接收的禮物',
  [Log.Gifts.ReceiveOneSkippedOnly]: '信箱只剩跳過的信件',
  [Log.Hearts.ReadRecords]: '讀取紀錄',
  [Log.Hearts.SaveRecords]: '儲存紀錄',
  [Log.Hearts.SendStart]: '開始送愛心',
  [Log.Hearts.SendDone]: '送愛心完成',
  [Log.Hearts.Screenful]: '這一頁送出的愛心',
  [Log.Hearts.ListEnd]: '已到排行榜底部',
  [Log.Hearts.ZeroScore]: '已到 0 分的好友',
  [Log.Hearts.TimeUp]: '送心時間結束',
  [Log.Report.Saved]: '已儲存問題回報',
  [Log.Report.Failed]: '無法儲存問題回報',
  [Log.Walk.Start]: '導覽紀錄中，請自行操作遊戲',
  [Log.Walk.Page]: '已紀錄畫面',
  [Log.Walk.Tap]: '已紀錄點擊',
  [Log.Walk.Done]: '導覽紀錄完成',
  [Log.Unlock.NowQueued]: '下一輪提升等級上限',
  [Log.Unlock.NowRefused]: '現在無法提升等級上限',
  [Log.Unlock.NowWaiting]: '本局結束後再提升等級上限',
  [Log.Unlock.NowYielded]: '先讓給提升等級上限',
  [Log.Unlock.Start]: '尋找已達等級上限的 Tsum',
  [Log.Unlock.Raised]: '已提升 Tsum 等級上限',
  [Log.Unlock.NextPage]: '八隻都已達上限，下一頁',
  [Log.Unlock.SortFailed]: '無法變更收藏排序',
  [Log.Unlock.SortRestored]: '已恢復收藏排序',
  [Log.Unlock.RaiseNotConfirmed]: '等級上限未提升，金幣不足？',
  [Log.Unlock.Retrying]: '提升失敗，重讀收藏頁面',
  [Log.Unlock.End]: '提升等級上限完成',
  [Log.Unlock.MyTsumCapped]: 'MyTsum 已達等級上限',
  [Log.Unlock.MyTsumStart]: '提升 MyTsum 等級上限',
  [Log.Unlock.MyTsumNotSelected]: '收藏頁面顯示的不是 MyTsum，不提升',
  [Log.Unlock.MyTsumBackoff]: 'MyTsum 提升失敗，稍後再試',
  [Log.Unlock.MyTsumEnd]: 'MyTsum 等級上限提升完成'
}

logRegisterStrings(Locale.Taiwan, LogsZhTw);
