// Every setting's default, in both the game and the settings compilations.
// The settings page's rows read their `default` from here, and the game
// script fills a start from it (`remoteStartSettings` in index.ts), so a
// device that never opened the page can still be started from GAP Companion.
// Typed as `Settings`, so a new required key is a build error until it has
// a default here.

var SettingDefaults: Readonly<Settings> = {
  [SettingKey.SkillType]: SkillType.Burst,
  [SettingKey.SkillLevel]: 6,
  [SettingKey.LorcanaCard]: false,
  [SettingKey.SkillAutoTap]: true,
  [SettingKey.SkillSettleMs]: 0,
  [SettingKey.NoSkillLastFeverSec]: 0,
  [SettingKey.SkillWaitingTime]: 0,
  [SettingKey.SkillReactivationTenths]: 0,
  [SettingKey.MaxChainsPerScan]: 3,
  [SettingKey.MaxChain]: 5,
  [SettingKey.BonusScore]: false,
  [SettingKey.BonusCoin]: false,
  [SettingKey.BonusExp]: false,
  [SettingKey.BonusTime]: false,
  [SettingKey.BonusBubble]: false,
  [SettingKey.Bonus5to4]: false,
  [SettingKey.BonusCombo]: false,
  [SettingKey.ReceiveAllHearts]: false,
  [SettingKey.ReceiveAllHeartsMinWait]: 40,
  [SettingKey.SendHeartsAuto]: false,
  [SettingKey.SendHeartsToZeroScore]: false,
  [SettingKey.SendHeartsMaxRuntime]: 0,
  [SettingKey.SendHeartsMinWait]: 26,
  [SettingKey.ReceiveHeartsOneByOne]: false,
  [SettingKey.ReceiveHeartsSkipRuby]: false,
  [SettingKey.ReceiveHeartsSkipMedals]: false,
  [SettingKey.ClaimAllWithoutCoins]: false,
  [SettingKey.MailOpenMax]: 2,
  [SettingKey.MailMinWait]: 25,
  [SettingKey.LinkReachPercent]: 190,
  [SettingKey.PrioritizeMyTsum]: true,
  [SettingKey.BubbleStrategy]: BubbleStrategy.OneMidChain,
  [SettingKey.HoldBubblesLastFeverSec]: 0,
  [SettingKey.UseFan]: false,
  [SettingKey.UnlockLevelHoursWait]: 0,
  [SettingKey.AutoUnlockMyTsumLevel]: false,
  [SettingKey.BuyBoxHoursWait]: 0,
  [SettingKey.BuyBoxType]: BoxType.Premium,
  [SettingKey.BuyBoxSize]: BoxPurchaseSize.One,
  [SettingKey.BuyBoxMaxPurchases]: 10,
  [SettingKey.SpecialScreenRatio]: false,
  [SettingKey.DeviceFps]: 60,
  [SettingKey.AutoLaunchApp]: true,
  [SettingKey.AutoPlayGame]: true,
  [SettingKey.ClickAssist]: false,
  [SettingKey.RoundDelayMinutes]: 0,
  [SettingKey.MaxRoundMinutes]: 0,
  [SettingKey.MaxRoundAction]: MaxRoundAction.Coast,
  [SettingKey.StopAfterGames]: 0,
  [SettingKey.StopAfterAction]: StopAfterAction.AutoPlayOff,
  [SettingKey.TrackRoundStats]: true,
  [SettingKey.ShareRoundStats]: false,
  [SettingKey.TsumAppRestartFrequency]: 0,
  [SettingKey.DebugLogs]: false,
  [SettingKey.DebugGame]: false,
  [SettingKey.Walkthrough]: false,
  [SettingKey.CollectUnknownScreens]: false,
  [SettingKey.PageHistoryDepth]: 20,
};
