// English -- the reference catalogue.
//
// Typed `UiStrings` rather than `UiStringsPartial`, so it is the one language
// that has to be complete: a new `UiText` member fails the build here until it
// has text, and every other language falls back to this one key by key. Loaded
// first, which is what makes it the fallback at runtime too (`i18nRegister`).
//
// Wording is free to change -- the key is the interface, not the sentence.

i18nRegister(Locale.English, 'English', {
    [UiText.TabGeneral]: 'General',
    [UiText.TabGameplay]: 'Gameplay',
    [UiText.TabChores]: 'Chores',
    [UiText.TabSkills]: 'Skills',
    [UiText.TabHearts]: 'Hearts',
    [UiText.TabAdvanced]: 'Advanced',
    [UiText.TabDebug]: 'Debug',

    [UiText.GroupDevice]: 'Device',
    [UiText.GroupRunOrder]: 'Run order',
    [UiText.GroupRunOrderHelp]: 'What the script will do, and in what order, with the settings as they are now.',
    [UiText.GroupSettingsCode]: 'Settings code',
    [UiText.GroupSettingsCodeHelp]: 'Copy how you play a round as one line of text, or paste someone else\'s.',
    [UiText.GroupPlaying]: 'Playing',
    [UiText.GroupBoardHelpers]: 'Board helpers',
    [UiText.GroupItems]: 'Items',
    [UiText.GroupItemsHelp]: 'Bought on the pre-round screen, so each one spends Coins every round.',
    [UiText.GroupLevelCaps]: 'Level caps',
    [UiText.GroupBoxes]: 'Boxes',
    [UiText.GroupBoxesHelp]: 'Buys from the Tsum Tsum Store between rounds. Rubies are never spent: the offer to trade them for Coins is always cancelled.',
    [UiText.GroupSkill]: 'Skill',
    [UiText.GroupTiming]: 'Timing',
    [UiText.GroupReceiveAll]: 'Receive all',
    [UiText.GroupMailbox]: 'Mailbox, one by one',
    [UiText.GroupSendHearts]: 'Send hearts',
    [UiText.GroupExperimental]: 'Experimental',
    [UiText.GroupExperimentalHelp]: 'Things may not work correctly in every scenario.',
    [UiText.GroupDiagnostics]: 'Diagnostics',

    [UiText.SettingLanguage]: 'Language',
    [UiText.SettingLanguageHelp]: 'The language this page and the Quick Bar are written in.',
    [UiText.SettingSpecialScreenRatio]: 'Special Screen Ratio (Long Screen) (Should start in game)',
    [UiText.SettingSpecialScreenRatioHelp]: 'For a long screen with uneven black bars above and below the game. Start the game yourself first: this does not work with Auto Launch.',
    [UiText.SettingDeviceFps]: 'Device frame rate',
    [UiText.SettingDeviceFpsHelp]: 'Scales how long self-dismissing screens stay up.',
    [UiText.SettingAutoLaunchApp]: 'Auto Launch Tsum App',
    [UiText.SettingAutoLaunchAppHelp]: 'Opens Tsum Tsum when the script starts. Leave it off if Special Screen Ratio is on.',
    [UiText.SettingShareSettings]: 'Share settings',
    [UiText.SettingExportPresets]: 'Export presets',
    [UiText.SettingExportPresetsHelp]: 'One settings code per preset. Paste a line back in above.',
    [UiText.SettingAutoPlayGame]: 'Auto Play Game',
    [UiText.SettingAutoPlayGameHelp]: 'Plays a round whenever no other job is due. Off leaves the chores and nothing else.',
    [UiText.SettingClickAssist]: 'Click Assist (connect on tap)',
    [UiText.SettingClickAssistHelp]: 'Replaces auto-play: you pick the tsum, the script draws the chain.',
    [UiText.SettingRoundDelay]: 'Delay between rounds (min)',
    [UiText.SettingRoundDelayHelp]: '0 plays straight on. Now ends a wait already running.',
    [UiText.SettingMaxRound]: 'Max round duration (min)',
    [UiText.SettingMaxRoundHelp]: '0 lets every round run its course. Otherwise the script gives up on a round that has lasted this long.',
    [UiText.SettingMaxRoundAction]: 'When a round runs long',
    [UiText.SettingMaxRoundActionHelp]: 'What to do once Max round duration is up. Only used when that is above 0.',
    [UiText.MaxRoundCoast]: 'Stop playing, let the clock run out',
    [UiText.MaxRoundStop]: 'Stop the script',
    [UiText.SettingMaxChainsPerScan]: 'Chains per board scan',
    [UiText.SettingMaxChainsPerScanHelp]: 'How many chains are linked before the board is looked at again. Fewer keeps the targets fresh, more spends less time scanning.',
    [UiText.SettingMaxChain]: 'Maximum Chain Number',
    [UiText.SettingMaxChainHelp]: 'The longest chain the script will draw. A low cap plays more, shorter chains, which suits a tsum that scores off chain count. Click Assist ignores it.',
    [UiText.SettingLinkReach]: 'Link reach (% of a tsum)',
    [UiText.SettingLinkReachHelp]: 'How far apart two tsums may be and still be linked. Too low and no long chain exists; too high and the game refuses the drag.',
    [UiText.SettingPrioritizeMyTsum]: 'Link MyTsum first',
    [UiText.SettingPrioritizeMyTsumHelp]: 'Fills the skill gauge faster.',
    [UiText.SettingTrackRoundStats]: 'Record round stats',
    [UiText.SettingTrackRoundStatsHelp]: 'One CSV per skill under tsum_record/.',
    [UiText.SettingBubbleStrategy]: 'Bubble Strategy',
    [UiText.SettingBubbleStrategyHelp]: 'A bubble popped inside a chain clears more, so the default hoards them for chains.',
    [UiText.SettingHoldBubblesLastFever]: 'Hold bubbles last fever seconds',
    [UiText.SettingHoldBubblesLastFeverHelp]: 'Leaves every bubble alone while a fever has this many seconds left, so they are there to pop into the first chains after it and refill the gauge faster. 0 never holds.',
    [UiText.SettingUseFan]: 'Use Fan?',
    [UiText.SettingUseFanHelp]: 'Shakes the board with the fan every few scans, to stir up what the chains left behind.',
    [UiText.SettingBonusScore]: '+Score',
    [UiText.SettingBonusScoreHelp]: 'A score bonus for the round.',
    [UiText.SettingBonusCoin]: '+Coin',
    [UiText.SettingBonusCoinHelp]: 'More Coins from the round.',
    [UiText.SettingBonusExp]: '+Exp',
    [UiText.SettingBonusExpHelp]: 'More experience from the round.',
    [UiText.SettingBonusTime]: '+Time',
    [UiText.SettingBonusTimeHelp]: 'A few more seconds of play.',
    [UiText.SettingBonusBubble]: '+Bubble',
    [UiText.SettingBonusBubbleHelp]: 'More bubbles on the board.',
    [UiText.SettingBonus5to4]: '5>4',
    [UiText.SettingBonus5to4Help]: 'One tsum colour fewer, so chains come easier.',
    [UiText.SettingBonusCombo]: '+Combo',
    [UiText.SettingBonusComboHelp]: 'More time to keep a combo going.',
    [UiText.SettingUnlockLevel]: 'Unlock Level every hours',
    [UiText.SettingUnlockLevelHelp]: '0 turns it off. Now runs one sweep straight away, ahead of everything but a round in progress, and starts the script if it is stopped.',
    [UiText.SettingUnlockMyTsumLevel]: 'Auto Unlock MyTsum Level',
    [UiText.SettingUnlockMyTsumLevelHelp]: 'When the level-up screen after a round shows "Raise level cap!" on your MyTsum, goes to the Tsum list and buys that one raise (consumes coins), then plays on. Only the selected tsum; the sweep above is separate.',
    [UiText.SettingBuyBox]: 'Buy boxes every hours',
    [UiText.SettingBuyBoxHelp]: '0 turns it off. Buys from the Tsum Tsum Store until it sells out or the Coins run out. Rubies are never spent. Now runs one sweep straight away, and starts the script if it is stopped.',
    [UiText.SettingBuyBoxType]: 'Box to buy',
    [UiText.SettingBuyBoxTypeHelp]: 'Only this box is bought, never another. Select Box and Pick-Up Capsule share the limited-time slot, so most of the time neither is on sale, and only one of them at a time.',
    [UiText.SettingBuyBoxSize]: 'Boxes per purchase',
    [UiText.SettingBuyBoxSizeHelp]: 'Ten takes the 10-Time Purchase where the box offers one; a box that only sells single ones is bought singly. Once the store refuses ten because the box is almost sold out, Ten stops and Ten, then one carries on singly until it sells out.',
    [UiText.SettingBuyBoxMax]: 'Purchases per sweep',
    [UiText.SettingBuyBoxMaxHelp]: 'The safety limit on a chore that spends Coins. A 10-Time purchase counts as one.',
    [UiText.BoxPremiumPlus]: 'Premium Box+',
    [UiText.BoxPremium]: 'Premium Box',
    [UiText.BoxSelect]: 'Select Box',
    [UiText.BoxCapsule]: 'Pick-Up Capsule',
    [UiText.BoxHappiness]: 'Happiness Box',
    [UiText.BoxSizeOne]: 'One at a time',
    [UiText.BoxSizeTen]: 'Ten at a time',
    [UiText.BoxSizeTenThenOne]: 'Ten, then one until sold out',
    [UiText.SettingSkillType]: 'Skill Type',
    [UiText.SettingSkillTypeHelp]: 'How the script plays the skill. Burst suits most tsums; the named ones are tuned for that tsum alone.',
    [UiText.SettingSkillLevel]: 'Skill Level',
    [UiText.SettingSkillLevelHelp]: 'Only read by the skills whose timing changes with it -- Cinderella, Cpt. Lightyear and both Coronation Elsa entries. Ignored by the rest.',
    [UiText.SettingSkillWaitingTime]: 'Skill Waiting time (sec)',
    [UiText.SettingSkillWaitingTimeHelp]: 'The most time the board is left alone after firing, so the skill can play out; play resumes as soon as the tsums have landed. Set it to cover a skill that clears bubbles after itself.',
    [UiText.SettingSkillSettle]: 'Wait for Settle (ms)',
    [UiText.SettingSkillSettleHelp]: 'Once the gauge is full, waits up to this long for the tsums the last chains cleared to drop back in before firing -- a skill fired onto a half-empty board clears very little. Fires as soon as the board holds still; while it is still moving, bubbles are popped as the Bubble Strategy allows. 0 fires at once.',
    [UiText.SettingNoSkillLastFever]: 'No skill last fever seconds',
    [UiText.SettingNoSkillLastFeverHelp]: 'Holds the skill back this near the end of a fever, so it can start the next one instead. 0 never holds.',
    [UiText.SettingSkillAutoTap]: 'Auto Tap Skill',
    [UiText.SettingSkillAutoTapHelp]: 'Fires the skill the moment the gauge fills, even mid-chain, rather than at the end of the board scan.',
    [UiText.SettingLorcanaCard]: 'Lorcana Card',
    [UiText.SettingLorcanaCardHelp]: 'Taps the transformation card when it appears, and clears the ink stones a Lorcana skill leaves behind.',
    [UiText.SettingReceiveAllHearts]: 'Receive All Hearts',
    [UiText.SettingReceiveAllHeartsHelp]: 'Empties the mailbox with one Claim All. Fast, but nobody gets a heart back.',
    [UiText.SettingRepeatWait]: 'Waiting time (min) before repeat',
    [UiText.SettingReceiveAllWaitHelp]: 'How long to wait before pressing Claim All again.',
    [UiText.SettingMailWaitHelp]: 'How long the mailbox is left alone once it is empty or the limit above is reached.',
    [UiText.SettingSendWaitHelp]: 'How long to wait before the next pass down the friends list.',
    [UiText.SettingReceiveOneByOne]: 'Receive Hearts One By One',
    [UiText.SettingReceiveOneByOneHelp]: 'Opens each mail in turn, which sends a heart back -- even to someone not on your friends list. Slower than Claim All.',
    [UiText.SettingSkipFirstPerson]: 'Skip first person',
    [UiText.SettingSkipFirstPersonHelp]: 'Leaves the top mail alone, for where it is an advertisement.',
    [UiText.SettingSkipRuby]: 'Skip Ruby',
    [UiText.SettingSkipRubyHelp]: 'Leaves Ruby gifts in the mailbox, taking the first mail under them and scrolling on when a screenful is all rubies.',
    [UiText.SettingSkipMedals]: 'Skip Medals',
    [UiText.SettingSkipMedalsHelp]: 'Leaves Mission Clear medals in the mailbox, taking the first mail under them and scrolling on when a screenful is all medals.',
    [UiText.SettingClaimAllOldMails]: 'Claim All old mails',
    [UiText.SettingClaimAllOldMailsHelp]: 'Takes the mails carrying Coins one by one first, then clears whatever is left with Claim All.',
    [UiText.SettingMailOpenMax]: 'Max Times to Open Mailbox',
    [UiText.SettingMailOpenMaxHelp]: 'How many times in a row the mailbox is opened before the next job. It stops early once the mailbox is empty.',
    [UiText.SettingSendHeartsAuto]: 'Auto Send Hearts',
    [UiText.SettingSendHeartsAutoHelp]: 'Works down your friends list sending hearts.',
    [UiText.SettingSendToZeroScore]: 'Send to 0 score',
    [UiText.SettingSendToZeroScoreHelp]: 'Also sends to friends with no score -- auto-senders, or people who have stopped playing.',
    [UiText.SettingSendMaxRuntime]: 'Max run time (min)',
    [UiText.SettingSendMaxRuntimeHelp]: '0 starts from the first place every time.',
    [UiText.SettingAppRestartFrequency]: 'Tsum app restart frequency (hours)',
    [UiText.SettingAppRestartFrequencyHelp]: 'Closes and reopens the game this often, to clear out a long run. 0 turns it off, and it needs Auto Launch Tsum App on.',
    [UiText.SettingBuildDate]: 'Build date: $BUILD_DATE',
    [UiText.SettingDebugLogs]: 'Debug logs',
    [UiText.SettingDebugLogsHelp]: 'More detail in the log.',
    [UiText.SettingBoardModel]: 'Board colour model',
    [UiText.SettingBoardModelHelp]: 'How the scan tells the tsum types apart. Chroma is what every round has played on. Radial also reads how much darker each tsum\'s rim is than its centre, which tells a face under dark hair from a plain one of the same colour. Experimental.',
    [UiText.BoardModelChroma]: 'Chroma (default)',
    [UiText.BoardModelRadial]: 'Radial (experimental)',
    [UiText.SettingClusterFragments]: 'Merge cluster fragments',
    [UiText.SettingClusterFragmentsHelp]: 'A scan often splits one tsum type into a big cluster and a few small ones, and the small ones are thrown away. This merges them back, down to the number of types on the board. Experimental.',
    [UiText.SettingDebugGame]: 'Debug game',
    [UiText.SettingDebugGameHelp]: 'Saves the screenshots the script works from, plus one per screen it visits. For development.',
    [UiText.SettingWalkthrough]: 'Walkthrough recorder (tsum_record/walkthrough)',
    [UiText.SettingWalkthroughHelp]: 'Drive the game yourself; the script records each screen, '
        + 'where you tapped, and what followed. Nothing else runs.',
    [UiText.SettingCollectUnknownScreens]: 'Collect unknown screens (tsum_record/corpus)',
    [UiText.SettingCollectUnknownScreensHelp]: 'Saves any screen the script cannot place, so it can be sent in and turned into a fix.',
    [UiText.SettingPageHistoryDepth]: 'Page history depth',
    [UiText.SettingPageHistoryDepthHelp]: 'Screens remembered. Debug game keeps a picture of every one of them; without it the last few are kept, which is what a report sends.',
    [UiText.SettingReportIssue]: 'Report a problem',
    [UiText.SettingReportIssueHelp]: 'Saves the screen, the screens before it, this run’s recent log and your settings to tsum_record/reports. Send it with Share in Run History.',
    [UiText.ReportNotePlaceholder]: 'What went wrong? (optional)',
    [UiText.ReportSaved]: 'Saved. Send it with Share in the app’s Run History.',
    [UiText.ReportFailed]: 'Nothing was saved. Start the script first, then try again.',
    [UiText.SettingDetectMyTsum]: 'Detect MyTsum',
    [UiText.SettingDetectMyTsumHelp]: 'Reads which tsum the game’s pre-round screen shows selected, without playing a round. Open that screen, stop the script, then press Detect: the answer goes on the banner and is kept here.',
    [UiText.DetectMyTsumFound]: '{name} ({tsum}) — score {score}, margin {margin}.',
    [UiText.DetectMyTsumNearest]: 'No confident match. Nearest: {name} ({tsum}) — score {score}, margin {margin}.',
    [UiText.DetectMyTsumRunUp]: 'The script is running and reads the tsum itself before every round. Stop it to test here.',
    [UiText.DetectMyTsumNoLibrary]: 'This build carries no tsum library.',
    [UiText.DetectMyTsumUnreadable]: 'The tsum icon could not be read. Is the game on the pre-round screen?',
    [UiText.DetectMyTsumFailed]: 'Nothing was read. Load the script first, then try again.',

    [UiText.BubbleOneMidChain]: 'One Bubble Mid Chain',
    [UiText.BubbleAllMidChain]: 'All Bubbles Mid Chain',
    [UiText.BubbleAllAsap]: 'All Bubbles ASAP',
    // The Quick Bar's chip. "Mid" is mid-chain and "Now" is as soon as they
    // land, so the three read as a scale from one bubble to all of them.
    [UiText.BubbleOneMidChainShort]: '1 mid',
    [UiText.BubbleAllMidChainShort]: 'All mid',
    [UiText.BubbleAllAsapShort]: 'All now',

    [UiText.SkillGroupBurst]: 'Burst',
    [UiText.SkillGroupBubble]: 'Bubble',
    [UiText.SkillGroupUnique]: 'Unique',

    // Drawn as a pill beside the name, so they are short and shouted.
    [UiText.StatusFlagAlpha]: 'ALPHA',
    [UiText.StatusFlagBeta]: 'BETA',

    [UiText.SkillBurst]: 'Burst',
    [UiText.SkillBurstBubbles]: 'Burst + clear bubbles',
    [UiText.SkillDonald]: 'Donald',
    [UiText.SkillHolidayDonald]: 'Holiday Donald',
    [UiText.SkillJediLuke]: 'Jedi Luke',
    [UiText.SkillMoana]: 'Moana',
    [UiText.SkillMarie]: 'Marie',
    [UiText.SkillMissBunny]: 'Miss Bunny',
    [UiText.SkillRabbit]: 'Rabbit',
    [UiText.SkillHornHatMickey]: 'Horn Hat Mickey',
    [UiText.SkillSnowWhite]: 'Snow White',
    [UiText.SkillCinderella]: 'Cinderella',
    [UiText.SkillSheriffWoody]: 'Sheriff Woody',
    [UiText.SkillCabbageMickey]: 'Cabbage Mickey',
    [UiText.SkillCptLightyear]: 'Cpt. Lightyear',
    [UiText.SkillCptLightyear120]: 'Cpt. Lightyear 120',
    [UiText.SkillLightningMcQueenPlus]: 'Lightning McQueen+',
    [UiText.SkillFormalBeast]: 'Formal Beast',
    [UiText.SkillGaston]: 'Gaston',
    [UiText.SkillTiaraMinniePlus]: 'Tiara Minnie+',
    [UiText.SkillCoronationElsa]: 'Coronation Day Elsa',
    [UiText.SkillCoronationElsaLegacy]: 'Coronation Elsa Legacy',
    [UiText.SkillRapunzelPlus]: 'Rapunzel+',
    [UiText.SkillLorcanaAurora]: 'Lorcana Aurora',
    [UiText.SkillPairTsum]: 'Pair Tsum',
    [UiText.SkillNoSkill]: 'No Skill',

    [UiText.ButtonCopy]: 'Copy',
    [UiText.ButtonPaste]: 'Paste',
    [UiText.ButtonNow]: 'Now',
    [UiText.ButtonApply]: 'Apply',
    [UiText.ButtonClose]: 'Close',
    [UiText.ButtonSaveFile]: 'Save file',
    [UiText.ButtonReport]: 'Report',
    [UiText.ButtonSaveReport]: 'Save report',
    [UiText.ButtonDetect]: 'Detect',

    [UiText.ChromeReset]: 'Reset Settings',
    [UiText.ChromeRestartNow]: 'Restart TsumTsum script now',
    [UiText.ChromeThemeToLight]: 'Switch to light mode',
    [UiText.ChromeThemeToDark]: 'Switch to dark mode',

    [UiText.ShareCopied]: 'Settings code copied. Paste it to whoever wants it.',
    [UiText.ShareCopyFailed]: 'No clipboard access here - copy the code below by hand.',
    [UiText.SharePasteEmpty]: 'No settings code on the clipboard - paste one below, then tap Apply.',
    [UiText.SharePastePrompt]: 'Paste a settings code below, then tap Apply.',
    [UiText.ShareOtherFormat]: 'That code is in a different version of the format and cannot be read '
        + 'here. Ask for a fresh copy.',
    [UiText.ShareNotACode]: 'That is not a settings code.',
    [UiText.ShareApplied]: 'Applied {applied} settings{from}.',
    [UiText.ShareAppliedSkipped]: 'Applied {applied} settings{from}, skipped {skipped}.',

    [UiText.PresetNone]: 'No preset',
    [UiText.PresetOpen]: 'Switch preset',
    [UiText.PresetManage]: 'Save preset',
    [UiText.PresetNameHint]: 'Preset name',
    [UiText.PresetSaveNew]: 'Save as new',
    [UiText.PresetUpdate]: 'Update',
    [UiText.PresetDelete]: 'Delete',
    [UiText.PresetSaved]: 'Saved {name}.',
    [UiText.PresetUpdated]: 'Updated {name}.',
    [UiText.PresetDeleted]: 'Deleted {name}.',
    [UiText.PresetNeedsName]: 'Give the preset a name first.',
    [UiText.PresetNameTaken]: '{name} is already saved — Update overwrites it.',
    [UiText.PresetUnknownName]: 'There is no preset called {name}.',
    [UiText.PresetFull]: 'No room for another preset; the limit is {max}.',
    [UiText.PresetStoreFailed]: 'The presets could not be saved on this device.',
    [UiText.PresetExportNone]: 'There are no presets to export yet.',
    [UiText.PresetExportCopied]: 'Copied every preset to the clipboard.',
    [UiText.PresetExportCopyFailed]: 'The clipboard refused it — the text is selected, so copy it by hand.',
    [UiText.PresetExportSaved]: 'Written to {path}.',
    [UiText.PresetExportNoEngine]: 'Press Play once first: the file is written by the script, not by this page.',
    [UiText.PresetExportFailed]: 'The file could not be written: {error}',

    [UiText.LogNoSettings]: 'No settings found, using default ones',
    [UiText.LogLoadSettings]: 'Load settings',
    [UiText.LogSaveSettings]: 'Save settings',
    [UiText.LogStartCommand]: 'Start command',

    [UiText.RunEvery]: 'every {amount}',
    [UiText.RunHours]: '{count} h',
    [UiText.RunMinutes]: '{count} min',
    [UiText.RunSeconds]: '{count} s',
    [UiText.RunWalkthrough]: 'Record what you do',
    [UiText.RunWalkthroughDetail]: 'Watches and writes down what you do. Nothing else is registered.',
    [UiText.RunMailbox]: 'Open the mailbox, one by one',
    [UiText.RunMailboxDetail]: 'At most {max} mails per pass.',
    [UiText.RunReceiveAll]: 'Receive all hearts',
    [UiText.RunSendHearts]: 'Send hearts',
    [UiText.RunSendHeartsLimited]: 'Stops after {minutes} min and carries on from there next time.',
    [UiText.RunSendHeartsUnlimited]: 'No time limit: a whole sweep from the top each time.',
    [UiText.RunRestartApp]: 'Restart the Tsum app',
    [UiText.RunRestartAppDetail]: 'The first one is a full period after the start, not at it.',
    [UiText.RunClickAssist]: 'Click Assist',
    [UiText.RunClickAssistDetail]: 'Replaces auto-play: you pick the tsum, the script links it.',
    [UiText.RunUnlockLevel]: 'Unlock a level',
    [UiText.RunBuyBoxes]: 'Buy boxes',
    [UiText.RunBuyBoxesDetail]: '{box}, {size}, up to {max} purchases. Stops on Sold Out or too few Coins; never spends Rubies.',
    [UiText.RunPlayRound]: 'Play a round',
    [UiText.RunPlayRoundDelay]: 'Waits {minutes} min between rounds. ',
    [UiText.RunPlayRoundCap]: 'Gives up on a round after {minutes} min: {action}. ',
    [UiText.RunItemsNone]: 'No bonus items.',
    [UiText.RunItemsSome]: 'Items set before each round: {items}.',
    [UiText.RunItemsSeparator]: ', ',
    [UiText.RunNoteRecording]: 'Recording mode: everything on screen is yours to do.',
    [UiText.RunNoteNothingPlays]: 'Nothing plays: Auto Play Game and Click Assist are both off.',
    [UiText.RunNoteOrder]: 'Everything is due the moment the script starts, so this is the order it '
        + 'goes in; after that each repeats on its own clock, and when two fall due '
        + 'together the one higher on this list goes first. A round is always played '
        + 'to the end, so a job that comes due mid-round waits for it. Five errors in '
        + 'a row from one job restart the game app.',
    [UiText.RunFlowTitle]: 'Each board scan, while a round is running:',

    [UiText.FlowScan]: 'scan the board',
    [UiText.FlowPopAll]: 'pop every bubble',
    [UiText.FlowPlan]: 'plan chains (up to {max} long, {reach}% reach)',
    [UiText.FlowMyTsumFirst]: 'MyTsum first',
    [UiText.FlowKeep]: 'keep {count}',
    [UiText.FlowTapSkill]: 'tap the skill if it filled',
    [UiText.FlowHoldBubblesFever]: 'hold bubbles in a fever\'s last {sec}s',
    [UiText.FlowLinkOneBubble]: 'link them (one bubble mid-chain)',
    [UiText.FlowLinkAllBubbles]: 'link them (every bubble mid-chain)',
    [UiText.FlowLink]: 'link them',
    [UiText.FlowFan]: 'fan every 4th scan',
    [UiText.FlowNoSkill]: 'no skill',
    [UiText.FlowSettleSkill]: 'wait up to {ms}ms for the board to refill',
    [UiText.FlowUseSkill]: 'use the skill: {skill} L{level}',
    [UiText.FlowLorcanaCard]: 'tap the Lorcana card if it showed up',
    [UiText.FlowBoardUp]: 'is the board still up?',

    [UiText.QbLevel]: 'Lv',
    [UiText.QbBonusCoin]: '+Coin',
    [UiText.QbBonus5to4]: '5>4',
    [UiText.QbScan]: 'Scan',
    [UiText.QbChain]: 'Chain',
    [UiText.QbPreset]: 'Preset',
    [UiText.QbBubble]: 'Bubble',
    [UiText.QbReport]: 'Report',
    [UiText.QbBase]: 'Base',
    [UiText.QbFinal]: 'Final',
    [UiText.QbRounds]: 'Rounds',
} satisfies UiStrings);
