// English -- the reference catalogue.
//
// Typed `UiStrings` rather than `UiStringsPartial`, so it is the one language
// that has to be complete: a new `UiText` member fails the build here until it
// has text, and every other language falls back to this one key by key. Loaded
// first, which is what makes it the fallback at runtime too (`i18nRegister`).
//
// Wording is free to change -- the key is the interface, not the sentence.

i18nRegister(Locale.English, 'English', {
    [UiText.TabGeneral]: 'General',
    [UiText.TabGameplay]: 'Gameplay',
    [UiText.TabChores]: 'Chores',
    [UiText.TabSkills]: 'Skills',
    [UiText.TabRound]: 'Round',
    [UiText.TabHearts]: 'Hearts',
    [UiText.TabDebug]: 'Debug',

    [UiText.GroupDevice]: 'Device',
    [UiText.GroupRunOrder]: 'Run order',
    [UiText.GroupRunOrderHelp]: 'What a run will do, in order, with these settings.',
    [UiText.GroupSettingsCode]: 'Settings code',
    [UiText.GroupSettingsCodeHelp]: 'Copy your round setup as one line, or paste someone else\'s.',
    [UiText.GroupRun]: 'Running',
    [UiText.GroupChains]: 'Chains',
    [UiText.GroupLinking]: 'Linking',
    [UiText.GroupBoardHelpers]: 'Board helpers',
    [UiText.GroupItems]: 'Round bonuses',
    [UiText.GroupItemsHelp]: 'Bought before each round, so each one costs Coins every round.',
    [UiText.GroupLevelCaps]: 'Level caps',
    [UiText.GroupBoxes]: 'Boxes',
    [UiText.GroupBoxesHelp]: 'Bought from the store between rounds. Rubies are never spent.',
    [UiText.GroupTsumList]: 'Tsum List',
    [UiText.GroupTsumListHelp]: 'A CSV of every Tsum you own, read off the collection.',
    [UiText.GroupSkill]: 'Skill',
    [UiText.GroupTiming]: 'Timing',
    [UiText.GroupReceiveAll]: 'Receive all',
    [UiText.GroupMailbox]: 'Mailbox, one by one',
    [UiText.GroupSendHearts]: 'Send hearts',
    [UiText.GroupExperimental]: 'Experimental',
    [UiText.GroupExperimentalHelp]: 'May not work in every case.',
    [UiText.GroupDiagnostics]: 'Diagnostics',

    [UiText.SettingLanguage]: 'Language',
    [UiText.SettingLanguageHelp]: 'For this page and the Quick Bar.',
    [UiText.SettingSpecialScreenRatio]: 'Special Screen Ratio (Long Screen) (Should start in game)',
    [UiText.SettingSpecialScreenRatioHelp]: 'For long screens with uneven black bars. Start the game yourself; not with Auto Launch.',
    [UiText.SettingDeviceFps]: 'Device frame rate',
    [UiText.SettingDeviceFpsHelp]: 'Scales how long self-dismissing screens stay up.',
    [UiText.SettingAutoLaunchApp]: 'Auto Launch Tsum App',
    [UiText.SettingAutoLaunchAppHelp]: 'Opens Tsum Tsum on start. Leave off with Special Screen Ratio.',
    [UiText.SettingShareSettings]: 'Share settings',
    [UiText.SettingShareListing]: 'Copy with settings list',
    [UiText.SettingShareListingHelp]: 'Adds the skill type and the settings changed from default.',
    [UiText.SettingExportPresets]: 'Export presets',
    [UiText.SettingExportPresetsHelp]: 'One settings code per preset; paste them back above to restore them.',
    [UiText.SettingAutoPlayGame]: 'Auto Play Game',
    [UiText.SettingAutoPlayGameHelp]: 'Plays rounds when no other job is due. Off runs chores only.',
    [UiText.SettingClickAssist]: 'Click Assist (connect on tap)',
    [UiText.SettingClickAssistHelp]: 'Replaces auto-play: you pick the tsum, the script draws the chain.',
    [UiText.SettingRoundDelay]: 'Delay between rounds (min)',
    [UiText.SettingRoundDelayHelp]: '0 plays straight on. Now ends a wait already running.',
    [UiText.SettingMaxRound]: 'Max round duration (min)',
    [UiText.SettingMaxRoundHelp]: 'Gives up on a round after this long. 0 = no limit.',
    [UiText.SettingMaxRoundAction]: 'When a round runs long',
    [UiText.SettingMaxRoundActionHelp]: 'What to do when Max round duration is up.',
    [UiText.MaxRoundCoast]: 'Stop playing, let the clock run out',
    [UiText.MaxRoundStop]: 'Stop the script',
    [UiText.SettingStopAfterGames]: 'Stop after games',
    [UiText.SettingStopAfterGamesHelp]: 'Rounds to play before the action below. 0 = never.',
    [UiText.SettingStopAfterAction]: 'When the games are played',
    [UiText.SettingStopAfterActionHelp]: 'What to do once Stop after games is reached.',
    [UiText.StopAfterAutoPlayOff]: 'Turn off Auto Play',
    [UiText.StopAfterPause]: 'Pause the script',
    [UiText.StopAfterStop]: 'Stop the script',
    [UiText.StopAfterAutoPlayOffShort]: 'Auto off',
    [UiText.StopAfterPauseShort]: 'Pause',
    [UiText.StopAfterStopShort]: 'Stop',
    [UiText.SettingMaxChainsPerScan]: 'Chains per board scan',
    [UiText.SettingMaxChainsPerScanHelp]: 'Chains drawn before the board is rescanned. Fewer is fresher, more is faster.',
    [UiText.SettingMaxChain]: 'Maximum Chain Number',
    [UiText.SettingMaxChainHelp]: 'Longest chain drawn. Low suits tsums that score off chain count.',
    [UiText.SettingLinkReach]: 'Link reach (% of a tsum)',
    [UiText.SettingLinkReachHelp]: 'Max gap between linked tsums. Too low: short chains; too high: drags refused.',
    [UiText.SettingPrioritizeMyTsum]: 'Link MyTsum first',
    [UiText.SettingPrioritizeMyTsumHelp]: 'Fills the skill gauge faster.',
    [UiText.SettingTrackRoundStats]: 'Record round stats',
    [UiText.SettingTrackRoundStatsHelp]: 'One CSV a day (UTC) under stats/: stats_YYYYMMDD.csv.',
    [UiText.SettingShareRoundStats]: 'Share round stats',
    [UiText.SettingShareRoundStatsHelp]: 'Sends new rows to the stats server about once a minute. Needs Record round stats, and a stats server set with network access allowed in GAP (Library > this script > settings).',
    [UiText.SettingBubbleStrategy]: 'Bubble Strategy',
    [UiText.SettingBubbleStrategyHelp]: 'A bubble popped mid-chain clears more; the default saves them for that.',
    [UiText.SettingHoldBubblesLastFever]: 'Hold bubbles last fever seconds',
    [UiText.SettingHoldBubblesLastFeverHelp]: 'Saves bubbles in a fever\'s last seconds to refill the gauge after it. 0 = off.',
    [UiText.SettingUseFan]: 'Use Fan?',
    [UiText.SettingUseFanHelp]: 'Shakes the board every few scans.',
    [UiText.SettingBonusScore]: '+Score',
    [UiText.SettingBonusScoreHelp]: 'A score bonus for the round.',
    [UiText.SettingBonusCoin]: '+Coin',
    [UiText.SettingBonusCoinHelp]: 'More Coins from the round.',
    [UiText.SettingBonusExp]: '+Exp',
    [UiText.SettingBonusExpHelp]: 'More experience from the round.',
    [UiText.SettingBonusTime]: '+Time',
    [UiText.SettingBonusTimeHelp]: 'A few more seconds of play.',
    [UiText.SettingBonusBubble]: '+Bubble',
    [UiText.SettingBonusBubbleHelp]: 'More bubbles on the board.',
    [UiText.SettingBonus5to4]: '5>4',
    [UiText.SettingBonus5to4Help]: 'One tsum colour fewer, so chains come easier.',
    [UiText.SettingBonusCombo]: '+Combo',
    [UiText.SettingBonusComboHelp]: 'More time to keep a combo going.',
    [UiText.SettingUnlockLevel]: 'Unlock Level every hours',
    [UiText.SettingUnlockLevelHelp]: 'Hours between sweeps, 0 = off. Now runs one right away.',
    [UiText.SettingUnlockMyTsumLevel]: 'Auto Unlock MyTsum Level',
    [UiText.SettingUnlockMyTsumLevelHelp]: 'Raises your MyTsum\'s level cap when a round ends with it capped (spends Coins).',
    [UiText.SettingBuyBox]: 'Buy boxes every hours',
    [UiText.SettingBuyBoxHelp]: 'Hours between sweeps, 0 = off. Buys until sold out or out of Coins. Now runs one right away.',
    [UiText.SettingExportTsumList]: 'Export Tsum list',
    [UiText.SettingExportTsumListHelp]: 'Taps through the collection by Date acquired and writes name, level, skill and date to stats/tsum_list_*.csv. Takes a few seconds per Tsum. Started from here, the run stops when it is done.',
    [UiText.SettingBuyBoxType]: 'Box to buy',
    [UiText.SettingBuyBoxTypeHelp]: 'Only this box. Select Box and Pick-Up Capsule share a limited-time slot.',
    [UiText.SettingBuyBoxSize]: 'Boxes per purchase',
    [UiText.SettingBuyBoxSizeHelp]: 'When the store refuses ten, Ten stops and Ten, then one finishes singly.',
    [UiText.SettingBuyBoxMax]: 'Purchases per sweep',
    [UiText.SettingBuyBoxMaxHelp]: 'Safety limit per sweep. A 10-Time purchase counts as one.',
    [UiText.BoxPremiumPlus]: 'Premium Box+',
    [UiText.BoxPremium]: 'Premium Box',
    [UiText.BoxSelect]: 'Select Box',
    [UiText.BoxCapsule]: 'Pick-Up Capsule',
    [UiText.BoxHappiness]: 'Happiness Box',
    [UiText.BoxSizeOne]: 'One at a time',
    [UiText.BoxSizeTen]: 'Ten at a time',
    [UiText.BoxSizeTenThenOne]: 'Ten, then one until sold out',
    [UiText.SettingSkillType]: 'Skill Type',
    [UiText.SettingSkillTypeHelp]: 'Burst suits most tsums; named ones are tuned for that tsum.',
    [UiText.SettingSkillLevel]: 'Skill Level',
    [UiText.SettingSkillLevelHelp]: 'Only used by Cinderella, Cpt. Lightyear and Coronation Elsa.',
    [UiText.SettingSkillWaitingTime]: 'Skill Waiting time (sec)',
    [UiText.SettingSkillWaitingTimeHelp]: 'Max time the board is left alone after firing; play resumes once tsums land.',
    [UiText.SettingSkillSettle]: 'Wait for Settle (s)',
    [UiText.SettingSkillSettleHelp]: 'Waits up to this long for the board to refill before firing. 0 fires at once.',
    [UiText.SettingSkillReactivation]: 'Delay Skill ReActivation (sec)',
    [UiText.SettingSkillReactivationHelp]: 'Holds a full gauge this long after firing, so a running skill is not restarted. 0 = off.',
    [UiText.SettingNoSkillLastFever]: 'No skill last fever seconds',
    [UiText.SettingNoSkillLastFeverHelp]: 'Holds the skill near a fever\'s end to start the next one. 0 = off.',
    [UiText.SettingSkillAutoTap]: 'Auto Tap Skill',
    [UiText.SettingSkillAutoTapHelp]: 'Fires the moment the gauge fills, even mid-chain.',
    [UiText.SettingLorcanaCard]: 'Lorcana Card',
    [UiText.SettingLorcanaCardHelp]: 'Taps the transformation card and clears the ink stones.',
    [UiText.SettingReceiveAllHearts]: 'Receive All Hearts',
    [UiText.SettingReceiveAllHeartsHelp]: 'One Claim All. Fast, but sends no hearts back.',
    [UiText.SettingRepeatWait]: 'Waiting time (min) before repeat',
    [UiText.SettingReceiveAllWaitHelp]: 'Wait before the next Claim All.',
    [UiText.SettingMailWaitHelp]: 'Wait once the mailbox is empty or the limit is reached.',
    [UiText.SettingSendWaitHelp]: 'Wait before the next pass down the friends list.',
    [UiText.SettingReceiveOneByOne]: 'Receive Hearts One By One',
    [UiText.SettingReceiveOneByOneHelp]: 'Opens each mail, sending a heart back to everyone. Slower than Claim All.',
    [UiText.SettingSkipRuby]: 'Skip Ruby',
    [UiText.SettingSkipRubyHelp]: 'Leaves Ruby gifts in the mailbox.',
    [UiText.SettingSkipMedals]: 'Skip Medals',
    [UiText.SettingSkipMedalsHelp]: 'Leaves Mission Clear medals in the mailbox.',
    [UiText.SettingClaimAllOldMails]: 'Claim All old mails',
    [UiText.SettingClaimAllOldMailsHelp]: 'Takes Coin mails one by one, then Claim All for the rest.',
    [UiText.SettingMailOpenMax]: 'Max Times to Open Mailbox',
    [UiText.SettingMailOpenMaxHelp]: 'Mailbox opens in a row before the next job; stops early when empty.',
    [UiText.SettingSendHeartsAuto]: 'Auto Send Hearts',
    [UiText.SettingSendHeartsAutoHelp]: 'Works down your friends list sending hearts.',
    [UiText.SettingSendToZeroScore]: 'Send to 0 score',
    [UiText.SettingSendToZeroScoreHelp]: 'Also friends with no score (inactive or auto-senders).',
    [UiText.SettingSendMaxRuntime]: 'Max run time (min)',
    [UiText.SettingSendMaxRuntimeHelp]: '0 starts from the first place every time.',
    [UiText.SettingAppRestartFrequency]: 'Tsum app restart frequency (min)',
    [UiText.SettingAppRestartFrequencyHelp]: 'Restarts the game this often on long runs. 0 = off; needs Auto Launch.',
    [UiText.SettingBuildDate]: 'Build date: $BUILD_DATE',
    [UiText.SettingDebugLogs]: 'Debug logs',
    [UiText.SettingDebugLogsHelp]: 'More detail in the log.',
    [UiText.SettingDebugGame]: 'Debug game',
    [UiText.SettingDebugGameHelp]: 'Saves working screenshots and one per screen visited. For development.',
    [UiText.SettingWalkthrough]: 'Walkthrough recorder (walkthrough/)',
    [UiText.SettingWalkthroughHelp]: 'Drive the game yourself; each screen and tap is recorded. Nothing else runs.',
    [UiText.SettingCollectUnknownScreens]: 'Collect unknown screens (corpus/)',
    [UiText.SettingCollectUnknownScreensHelp]: 'Saves screens the script cannot recognise, to send in for a fix.',
    [UiText.SettingPageHistoryDepth]: 'Page history depth',
    [UiText.SettingPageHistoryDepthHelp]: 'Screens remembered for a report. Debug game saves a picture of each.',
    [UiText.SettingReportIssue]: 'Report a problem',
    [UiText.SettingReportIssueHelp]: 'Saves the screen, recent screens, log and settings. Send it from Run History.',
    [UiText.ReportNotePlaceholder]: 'What went wrong? (optional)',
    [UiText.ReportSaved]: 'Saved. Send it with Share in the app’s Run History.',
    [UiText.ReportFailed]: 'Nothing was saved. Start the script first, then try again.',
    [UiText.SettingDetectMyTsum]: 'Detect MyTsum',
    [UiText.SettingDetectMyTsumHelp]: 'Reads the selected tsum off the pre-round screen. Open it, stop the script, press Detect.',
    [UiText.DetectMyTsumFound]: '{name} ({tsum}) — score {score}, margin {margin}.',
    [UiText.DetectMyTsumNearest]: 'No confident match. Nearest: {name} ({tsum}) — score {score}, margin {margin}.',
    [UiText.DetectMyTsumRunUp]: 'The script is running and reads the tsum itself before every round. Stop it to test here.',
    [UiText.DetectMyTsumNoLibrary]: 'This build carries no tsum library.',
    [UiText.DetectMyTsumUnreadable]: 'The tsum icon could not be read. Is the game on the pre-round screen?',
    [UiText.DetectMyTsumFailed]: 'Nothing was read. Load the script first, then try again.',

    [UiText.BubbleOneMidChain]: 'One Bubble Mid Chain',
    [UiText.BubbleAllMidChain]: 'All Bubbles Mid Chain',
    [UiText.BubbleSaveOneMidChain]: 'Save One Mid Chain',
    [UiText.BubbleSaveOne]: 'Save One',
    [UiText.BubbleAllAsap]: 'All Bubbles ASAP',
    // The Quick Bar's chip. "Mid" is mid-chain and "Now" is as soon as they
    // land, so the three read as a scale from one bubble to all of them.
    [UiText.BubbleOneMidChainShort]: '1 mid',
    [UiText.BubbleAllMidChainShort]: 'All mid',
    [UiText.BubbleSaveOneMidChainShort]: 'Save 1 mid',
    [UiText.BubbleSaveOneShort]: 'Save 1',
    [UiText.BubbleAllAsapShort]: 'All now',

    [UiText.SkillGroupBurst]: 'Burst',
    [UiText.SkillGroupBubble]: 'Bubble',
    [UiText.SkillGroupUnique]: 'Unique',

    // Drawn as a pill beside the name, so they are short and shouted.
    [UiText.StatusFlagAlpha]: 'ALPHA',
    [UiText.StatusFlagBeta]: 'BETA',

    [UiText.SkillBurst]: 'Burst',
    [UiText.SkillBurstBubbles]: 'Burst + clear bubbles',
    [UiText.SkillDonald]: 'Donald',
    [UiText.SkillHolidayDonald]: 'Holiday Donald',
    [UiText.SkillJediLuke]: 'Jedi Luke',
    [UiText.SkillMoana]: 'Moana',
    [UiText.SkillMarie]: 'Marie',
    [UiText.SkillMissBunny]: 'Miss Bunny',
    [UiText.SkillRabbit]: 'Rabbit',
    [UiText.SkillHornHatMickey]: 'Horn Hat Mickey',
    [UiText.SkillSnowWhite]: 'Snow White',
    [UiText.SkillCinderella]: 'Cinderella',
    [UiText.SkillSheriffWoody]: 'Sheriff Woody',
    [UiText.SkillCabbageMickey]: 'Cabbage Mickey',
    [UiText.SkillCptLightyear]: 'Cpt. Lightyear',
    [UiText.SkillCptLightyear120]: 'Cpt. Lightyear 120',
    [UiText.SkillLightningMcQueenPlus]: 'Lightning McQueen+',
    [UiText.SkillNightmareSet]: 'Nightmare Before Christmas (Set)',
    [UiText.SkillVillainsSet]: 'Disney Villains (Set)',
    [UiText.SkillFormalBeast]: 'Formal Beast',
    [UiText.SkillGaston]: 'Gaston',
    [UiText.SkillTiaraMinniePlus]: 'Tiara Minnie+',
    [UiText.SkillCoronationElsa]: 'Coronation Day Elsa',
    [UiText.SkillRapunzelPlus]: 'Rapunzel+',
    [UiText.SkillLorcanaAurora]: 'Lorcana Aurora',
    [UiText.SkillPairTsum]: 'Pair Tsum',
    [UiText.SkillNoSkill]: 'No Skill',

    [UiText.ButtonCopy]: 'Copy',
    [UiText.ButtonPaste]: 'Paste',
    [UiText.ButtonNow]: 'Now',
    [UiText.ButtonApply]: 'Apply',
    [UiText.ButtonClose]: 'Close',
    [UiText.ButtonSaveFile]: 'Save file',
    [UiText.ButtonReport]: 'Report',
    [UiText.ButtonSaveReport]: 'Save report',
    [UiText.ButtonDetect]: 'Detect',
    [UiText.CompanionConfirmSpend]: 'This lets GAP spend coins while you are not watching. Change it?',
    [UiText.CompanionConfirmSpendNow]: 'This spends coins. Do it now?',

    [UiText.ChromeReset]: 'Reset Settings',
    [UiText.ChromeRestartNow]: 'Restart TsumTsum script now',
    [UiText.ChromeThemeToLight]: 'Switch to light mode',
    [UiText.ChromeThemeToDark]: 'Switch to dark mode',
    [UiText.ChromeAppearance]: 'Appearance',
    [UiText.ChromeAppearanceClose]: 'Close',
    [UiText.ChromeStyle]: 'Style',
    [UiText.ChromeStyleAccessible]: 'Accessible',
    [UiText.ChromeStyleFelt]: 'Felt',
    [UiText.ChromeTheme]: 'Theme',
    [UiText.ChromeThemeDark]: 'Dark',
    [UiText.ChromeThemeLight]: 'Light',
    [UiText.ChromeThemeDevice]: 'Device',
    [UiText.ChromeSize]: 'Size',
    [UiText.ChromeSizeXs]: 'Extra small',
    [UiText.ChromeSizeS]: 'Small',
    [UiText.ChromeSizeM]: 'Medium',
    [UiText.ChromeSizeL]: 'Large',
    [UiText.ChromeSizeFeltNote]: 'Size applies to the Accessible style.',
    [UiText.ChromeMoreTabs]: 'Show more tabs',
    [UiText.ChromeCopyCode]: 'Code',
    [UiText.ChromeCopyCodeLabel]: 'Copy settings code',
    [UiText.ChromeCopied]: 'Copied',
    [UiText.ChromeCopyFailed]: 'Failed',

    [UiText.ShareCopied]: 'Settings code copied. Paste it to whoever wants it.',
    [UiText.ShareCopyFailed]: 'No clipboard access here - copy the code below by hand.',
    [UiText.SharePasteEmpty]: 'No settings code on the clipboard - paste one below, then tap Apply.',
    [UiText.SharePastePrompt]: 'Paste a settings code below, then tap Apply.',
    [UiText.ShareOtherFormat]: 'That code is in a different version of the format and cannot be read '
        + 'here. Ask for a fresh copy.',
    [UiText.ShareNotACode]: 'That is not a settings code.',
    [UiText.ShareListingOn]: 'On',
    [UiText.ShareListingOff]: 'Off',
    [UiText.ShareApplied]: 'Applied {applied} settings{from}.',
    [UiText.ShareAppliedSkipped]: 'Applied {applied} settings{from}, skipped {skipped}.',

    [UiText.PresetNone]: 'No preset',
    [UiText.PresetOpen]: 'Switch preset',
    [UiText.PresetManage]: 'Save preset',
    [UiText.PresetNameHint]: 'Preset name',
    [UiText.PresetSaveNew]: 'Save as new',
    [UiText.PresetUpdate]: 'Update',
    [UiText.PresetDelete]: 'Delete',
    [UiText.PresetSaved]: 'Saved {name}.',
    [UiText.PresetUpdated]: 'Updated {name}.',
    [UiText.PresetDeleted]: 'Deleted {name}.',
    [UiText.PresetNeedsName]: 'Give the preset a name first.',
    [UiText.PresetNameTaken]: '{name} is already saved — Update overwrites it.',
    [UiText.PresetUnknownName]: 'There is no preset called {name}.',
    [UiText.PresetFull]: 'No room for another preset; the limit is {max}.',
    [UiText.PresetStoreFailed]: 'The presets could not be saved on this device.',
    [UiText.PresetExportNone]: 'There are no presets to export yet.',
    [UiText.PresetExportCopied]: 'Copied every preset to the clipboard.',
    [UiText.PresetExportCopyFailed]: 'The clipboard refused it — the text is selected, so copy it by hand.',
    [UiText.PresetExportSaved]: 'Written to {path}.',
    [UiText.PresetExportNoEngine]: 'Press Play once first: the file is written by the script, not by this page.',
    [UiText.PresetExportFailed]: 'The file could not be written: {error}',
    [UiText.PresetImported]: 'Saved presets: {names}.',

    [UiText.LogNoSettings]: 'No settings found, using default ones',
    [UiText.LogLoadSettings]: 'Load settings',
    [UiText.LogSaveSettings]: 'Save settings',
    [UiText.LogStartCommand]: 'Start command',

    [UiText.RunEvery]: 'every {amount}',
    [UiText.RunHours]: '{count} h',
    [UiText.RunMinutes]: '{count} min',
    [UiText.RunSeconds]: '{count} s',
    [UiText.RunWalkthrough]: 'Record what you do',
    [UiText.RunWalkthroughDetail]: 'Watches and writes down what you do. Nothing else is registered.',
    [UiText.RunMailbox]: 'Open the mailbox, one by one',
    [UiText.RunMailboxDetail]: 'At most {max} mails per pass.',
    [UiText.RunReceiveAll]: 'Receive all hearts',
    [UiText.RunSendHearts]: 'Send hearts',
    [UiText.RunSendHeartsLimited]: 'Stops after {minutes} min and carries on from there next time.',
    [UiText.RunSendHeartsUnlimited]: 'No time limit: a whole sweep from the top each time.',
    [UiText.RunRestartApp]: 'Restart the Tsum app',
    [UiText.RunRestartAppDetail]: 'The first one is a full period after the start, not at it.',
    [UiText.RunClickAssist]: 'Click Assist',
    [UiText.RunClickAssistDetail]: 'Replaces auto-play: you pick the tsum, the script links it.',
    [UiText.RunUnlockLevel]: 'Unlock a level',
    [UiText.RunBuyBoxes]: 'Buy boxes',
    [UiText.RunBuyBoxesDetail]: '{box}, {size}, up to {max} purchases. Stops on Sold Out or too few Coins; never spends Rubies.',
    [UiText.RunPlayRound]: 'Play a round',
    [UiText.RunWorkflow]: 'Run a workflow',
    [UiText.RunWorkflowDetail]: 'Started from GAP Companion: its steps replace the jobs above.',
    [UiText.RunPlayRoundDelay]: 'Waits {minutes} min between rounds. ',
    [UiText.RunPlayRoundCap]: 'Gives up on a round after {minutes} min: {action}. ',
    [UiText.RunPlayRoundStopAfter]: 'After {games} games: {action}. ',
    [UiText.RunItemsNone]: 'No bonus items.',
    [UiText.RunItemsSome]: 'Items set before each round: {items}.',
    [UiText.RunItemsSeparator]: ', ',
    [UiText.RunNoteRecording]: 'Recording mode: everything on screen is yours to do.',
    [UiText.RunNoteNothingPlays]: 'Nothing plays: Auto Play Game and Click Assist are both off.',
    [UiText.RunNoteOrder]: 'Everything is due the moment the script starts, so this is the order it '
        + 'goes in; after that each repeats on its own clock, and when two fall due '
        + 'together the one higher on this list goes first. A round is always played '
        + 'to the end, so a job that comes due mid-round waits for it. Five errors in '
        + 'a row from one job restart the game app.',
    [UiText.RunFlowTitle]: 'Each board scan, while a round is running:',

    [UiText.FlowScan]: 'scan the board',
    [UiText.FlowPopAll]: 'pop every bubble',
    [UiText.FlowPopAllButOne]: 'pop every bubble but one',
    [UiText.FlowPlan]: 'plan chains (up to {max} long, {reach}% reach)',
    [UiText.FlowMyTsumFirst]: 'MyTsum first',
    [UiText.FlowKeep]: 'keep {count}',
    [UiText.FlowTapSkill]: 'tap the skill if it filled',
    [UiText.FlowHoldBubblesFever]: 'hold bubbles in a fever\'s last {sec}s',
    [UiText.FlowLinkOneBubble]: 'link them (one bubble mid-chain)',
    [UiText.FlowLinkAllButOne]: 'link them (all but one bubble mid-chain)',
    [UiText.FlowLinkAllBubbles]: 'link them (every bubble mid-chain)',
    [UiText.FlowLink]: 'link them',
    [UiText.FlowFan]: 'fan every 4th scan',
    [UiText.FlowNoSkill]: 'no skill',
    [UiText.FlowSettleSkill]: 'wait up to {sec}s for the board to refill',
    [UiText.FlowUseSkill]: 'use the skill: {skill} L{level}',
    [UiText.FlowLorcanaCard]: 'tap the Lorcana card if it showed up',
    [UiText.FlowBoardUp]: 'is the board still up?',

    [UiText.QbLevel]: 'Lv',
    [UiText.QbBonusCoin]: '+Coin',
    [UiText.QbBonus5to4]: '5>4',
    [UiText.QbGames]: 'Games',
    [UiText.QbThen]: 'Then',
    [UiText.QbStopAfterRound]: 'Last round',
    // U+FE0E keeps the heart a text glyph rather than an emoji.
    [UiText.QbSendHearts]: '\u2665\uFE0E Send',
    [UiText.QbReceiveOneByOne]: '\u2665\uFE0E 1-by-1',
    [UiText.QbUnlockNow]: 'Lvl',
    [UiText.QbCopyShare]: 'Copy code',
    [UiText.QbCodeCopied]: 'Settings code copied',
    [UiText.QbCodeNotCopied]: 'Could not copy the settings code',
    [UiText.QbCopyStats]: 'Copy statistics',
    [UiText.QbStatsCopied]: 'Statistics copied',
    [UiText.QbStatsNotCopied]: 'Could not copy the statistics',
    [UiText.QbLevelsAlreadyQueued]: 'Level caps are already queued',
    [UiText.QbLevelsNotQueued]: 'Could not queue raising level caps',
    [UiText.QbPage]: 'Switch page',
    [UiText.QbReadout]: 'Coins or times',
    [UiText.QbScan]: 'Scan',
    [UiText.QbChain]: 'Chain',
    [UiText.QbPreset]: 'Preset',
    [UiText.QbBubble]: 'Bubble',
    [UiText.QbAutoPlay]: 'Auto Play',
    [UiText.QbBase]: 'Base',
    [UiText.QbFinal]: 'Final',
    [UiText.QbMedals]: 'Medals',
    [UiText.QbRounds]: 'Rounds',
    [UiText.QbAvgRound]: 'Avg',
    [UiText.QbInRounds]: 'Played',
    [UiText.QbRunning]: 'Run',
    [UiText.QbStep]: 'Step',
} satisfies UiStrings);
