// Japanese.
//
// `UiStringsPartial`, so it may be incomplete: anything not here falls back to
// English at runtime. `npm run i18n:check` lists what is still missing.
//
// "Bubble" is ボム throughout: that is what the Japanese build of the game
// calls them. Missing on purpose, as in `src/uiZhTw.ts`: the Quick Bar strip
// (`qb.*`), the box names (`box.*`) and the skill names (`skill.*`), which are
// read off the game's own wording -- an English label beats a guessed one.

i18nRegister(Locale.Japanese, '日本語', {
    [UiText.TabGeneral]: '一般',
    [UiText.TabGameplay]: 'プレイ',
    [UiText.TabChores]: '雑務',
    [UiText.TabSkills]: 'スキル',
    [UiText.TabRound]: 'ラウンド',
    [UiText.TabHearts]: 'ハート',
    [UiText.TabDebug]: 'デバッグ',

    [UiText.GroupDevice]: 'デバイス',
    [UiText.GroupRunOrder]: '実行順序',
    [UiText.GroupRunOrderHelp]: 'この設定で実行される内容を順に表示します。',
    [UiText.GroupSettingsCode]: '設定コード',
    [UiText.GroupSettingsCodeHelp]: 'ラウンドの設定を1行でコピー、または他の人の設定を貼り付けます。',
    [UiText.GroupRun]: '実行',
    [UiText.GroupChains]: 'チェーン',
    [UiText.GroupLinking]: 'つなぎ方',
    [UiText.GroupBoardHelpers]: '盤面補助',
    [UiText.GroupItems]: 'アイテム',
    [UiText.GroupItemsHelp]: '毎ラウンド開始前に購入するため、毎回コインを消費します。',
    [UiText.GroupLevelCaps]: 'レベル上限',
    [UiText.GroupBoxes]: 'BOX',
    [UiText.GroupBoxesHelp]: 'ラウンドの合間にショップで購入します。ルビーは使いません。',
    [UiText.GroupSkill]: 'スキル',
    [UiText.GroupTiming]: 'タイミング',
    [UiText.GroupReceiveAll]: '一括受け取り',
    [UiText.GroupMailbox]: '1通ずつ受け取り',
    [UiText.GroupSendHearts]: 'ハートを送る',
    [UiText.GroupExperimental]: '実験的機能',
    [UiText.GroupExperimentalHelp]: 'すべての場面で動作するとは限りません。',
    [UiText.GroupDiagnostics]: '診断',

    [UiText.SettingLanguage]: '言語',
    [UiText.SettingLanguageHelp]: 'このページとクイックバーの言語。',
    [UiText.SettingSpecialScreenRatio]: '特殊な画面比率（縦長画面）（ゲーム内で開始）',
    [UiText.SettingSpecialScreenRatioHelp]: '黒帯が不均等な縦長画面向け。ゲームは手動で起動してください（自動起動は不可）。',
    [UiText.SettingDeviceFps]: 'デバイスのフレームレート',
    [UiText.SettingDeviceFpsHelp]: '自動で閉じる画面の表示時間を調整します。',
    [UiText.SettingAutoLaunchApp]: 'ツムツムを自動起動',
    [UiText.SettingAutoLaunchAppHelp]: '開始時にツムツムを起動します。特殊な画面比率とは併用しないでください。',
    [UiText.SettingShareSettings]: '設定を共有',
    [UiText.SettingShareListing]: '設定一覧も付けてコピー',
    [UiText.SettingShareListingHelp]: 'スキルの種類と、初期設定から変えた設定を付けます。',
    [UiText.SettingExportPresets]: 'プリセットを書き出す',
    [UiText.SettingExportPresetsHelp]: 'プリセットごとに設定コードを1つ。上の欄に貼り付けると戻せます。',
    [UiText.SettingAutoPlayGame]: '自動プレイ',
    [UiText.SettingAutoPlayGameHelp]: '他の作業がないときにラウンドをプレイします。オフなら雑務のみ。',
    [UiText.SettingClickAssist]: 'クリックアシスト（タップでつなぐ）',
    [UiText.SettingClickAssistHelp]: '自動プレイの代わりに、選んだツムをスクリプトがつなぎます。',
    [UiText.SettingRoundDelay]: 'ラウンド間の待機（分）',
    [UiText.SettingRoundDelayHelp]: '0 で続けてプレイ。「今すぐ」で実行中の待機を終了します。',
    [UiText.SettingMaxRound]: 'ラウンドの最大時間（分）',
    [UiText.SettingMaxRoundHelp]: 'この時間を過ぎたらラウンドを諦めます。0 = 無制限。',
    [UiText.SettingMaxRoundAction]: 'ラウンドが長引いたとき',
    [UiText.SettingMaxRoundActionHelp]: 'ラウンドの最大時間に達したときの動作。',
    [UiText.MaxRoundCoast]: '操作をやめて時間切れを待つ',
    [UiText.MaxRoundStop]: 'スクリプトを停止',
    [UiText.SettingStopAfterGames]: '指定ゲーム数で停止',
    [UiText.SettingStopAfterGamesHelp]: 'この数のラウンドを遊んだら下の動作をします。0 = しない。',
    [UiText.SettingStopAfterAction]: 'ゲーム数に達したとき',
    [UiText.SettingStopAfterActionHelp]: '指定ゲーム数に達したときの動作。',
    [UiText.StopAfterAutoPlayOff]: '自動プレイをオフ',
    [UiText.StopAfterPause]: 'スクリプトを一時停止',
    [UiText.StopAfterStop]: 'スクリプトを停止',
    [UiText.StopAfterAutoPlayOffShort]: '自動オフ',
    [UiText.StopAfterPauseShort]: '一時停止',
    [UiText.StopAfterStopShort]: '停止',
    [UiText.SettingMaxChainsPerScan]: '1スキャンあたりのチェーン数',
    [UiText.SettingMaxChainsPerScanHelp]: '盤面を再スキャンするまでに引くチェーン数。少ないほど正確、多いほど速い。',
    [UiText.SettingMaxChain]: '最大チェーン数',
    [UiText.SettingMaxChainHelp]: '引くチェーンの最長。チェーン数で得点するツムには低めが向いています。',
    [UiText.SettingLinkReach]: 'つなぐ距離（ツム幅の%）',
    [UiText.SettingLinkReachHelp]: 'つなぐツム同士の最大間隔。低すぎるとチェーンが短く、高すぎるとなぞりが通りません。',
    [UiText.SettingPrioritizeMyTsum]: 'マイツムを優先してつなぐ',
    [UiText.SettingPrioritizeMyTsumHelp]: 'スキルゲージが早くたまります。',
    [UiText.SettingTrackRoundStats]: 'ラウンド統計を記録',
    [UiText.SettingTrackRoundStatsHelp]: '1日 (UTC) ごとに CSV を1つ stats/ に保存します: stats_YYYYMMDD.csv。',
    [UiText.SettingShareRoundStats]: 'ラウンド統計を共有',
    [UiText.SettingShareRoundStatsHelp]: '新しい行を約1分ごとに統計サーバーへ送信します。「ラウンド統計を記録」と、GAPでの統計サーバーの設定とネットワークアクセスの許可（ライブラリ > このスクリプト > 設定）が必要です。',
    [UiText.SettingBubbleStrategy]: 'ボムの使い方',
    [UiText.SettingBubbleStrategyHelp]: 'チェーン途中で割ったボムはより多く消します。デフォルトはそのためにボムを残します。',
    [UiText.SettingHoldBubblesLastFever]: 'フィーバー終盤にボムを残す秒数',
    [UiText.SettingHoldBubblesLastFeverHelp]: 'フィーバー最後の数秒はボムを残し、終了後のゲージ回復に使います。0 = オフ。',
    [UiText.SettingUseFan]: 'ファンを使う',
    [UiText.SettingUseFanHelp]: '数回のスキャンごとに盤面を揺らします。',
    [UiText.SettingBonusScore]: '+スコア',
    [UiText.SettingBonusScoreHelp]: 'そのラウンドのスコアボーナス。',
    [UiText.SettingBonusCoin]: '+コイン',
    [UiText.SettingBonusCoinHelp]: 'そのラウンドで得るコインが増えます。',
    [UiText.SettingBonusExp]: '+経験値',
    [UiText.SettingBonusExpHelp]: 'そのラウンドで得る経験値が増えます。',
    [UiText.SettingBonusTime]: '+タイム',
    [UiText.SettingBonusTimeHelp]: 'プレイ時間が数秒延びます。',
    [UiText.SettingBonusBubble]: '+ボム',
    [UiText.SettingBonusBubbleHelp]: '盤面のボムが増えます。',
    [UiText.SettingBonus5to4]: '5→4',
    [UiText.SettingBonus5to4Help]: 'ツムの種類が1つ減り、つなぎやすくなります。',
    [UiText.SettingBonusCombo]: '+コンボ',
    [UiText.SettingBonusComboHelp]: 'コンボが続く時間が延びます。',
    [UiText.SettingUnlockLevel]: 'レベル上限解放の間隔（時間）',
    [UiText.SettingUnlockLevelHelp]: '実行の間隔（時間）、0 = オフ。「今すぐ」で即実行します。',
    [UiText.SettingUnlockMyTsumLevel]: 'マイツムのレベル上限を自動解放',
    [UiText.SettingUnlockMyTsumLevelHelp]: 'ラウンド終了時にマイツムが上限なら、上限を解放します（コインを消費）。',
    [UiText.SettingBuyBox]: 'BOX購入の間隔（時間）',
    [UiText.SettingBuyBoxHelp]: '実行の間隔（時間）、0 = オフ。売り切れかコイン不足まで購入します。「今すぐ」で即実行します。',
    [UiText.SettingBuyBoxType]: '購入するBOX',
    [UiText.SettingBuyBoxTypeHelp]: 'このBOXのみ購入。Select Box と Pick-Up Capsule は期間限定枠を共有します。',
    [UiText.SettingBuyBoxSize]: '1回の購入数',
    [UiText.SettingBuyBoxSizeHelp]: 'ショップが10連を断ったとき、「10連」は停止し、「10連→1回ずつ」は1回ずつ買い切ります。',
    [UiText.SettingBuyBoxMax]: '1回あたりの購入上限',
    [UiText.SettingBuyBoxMaxHelp]: '1回の実行での安全上限。10連は1回と数えます。',
    [UiText.BoxSizeOne]: '1回ずつ',
    [UiText.BoxSizeTen]: '10連',
    [UiText.BoxSizeTenThenOne]: '10連→売り切れまで1回ずつ',
    [UiText.SettingSkillType]: 'スキルタイプ',
    [UiText.SettingSkillTypeHelp]: 'ほとんどのツムは Burst で十分。名前付きはそのツム向けの調整です。',
    [UiText.SettingSkillLevel]: 'スキルレベル',
    [UiText.SettingSkillLevelHelp]: 'Cinderella、Cpt. Lightyear、Coronation Elsa のみ使用します。',
    [UiText.SettingSkillWaitingTime]: 'スキル待機時間（秒）',
    [UiText.SettingSkillWaitingTimeHelp]: '発動後に盤面を放置する最大時間。ツムが落ちきればプレイを再開します。',
    [UiText.SettingSkillSettle]: '盤面の落ち着き待ち（秒）',
    [UiText.SettingSkillSettleHelp]: '発動前に盤面が埋まるのを最大この時間待ちます。0 で即発動。',
    [UiText.SettingSkillReactivation]: 'スキル再発動の遅延（秒）',
    [UiText.SettingSkillReactivationHelp]: '発動後この時間は満タンのゲージを保持し、発動中のスキルをやり直させません。0 = オフ。',
    [UiText.SettingNoSkillLastFever]: 'フィーバー終盤にスキルを控える秒数',
    [UiText.SettingNoSkillLastFeverHelp]: 'フィーバー終了間際はスキルを温存し、次のフィーバーにつなげます。0 = オフ。',
    [UiText.SettingSkillAutoTap]: 'スキルを自動タップ',
    [UiText.SettingSkillAutoTapHelp]: 'ゲージが満タンになった瞬間、チェーン途中でも発動します。',
    [UiText.SettingLorcanaCard]: 'Lorcana カード',
    [UiText.SettingLorcanaCardHelp]: '変身カードをタップし、インクストーンを消します。',
    [UiText.SettingReceiveAllHearts]: 'ハートを一括受け取り',
    [UiText.SettingReceiveAllHeartsHelp]: '「すべて受け取る」を1回。速いですが、ハートは送り返しません。',
    [UiText.SettingRepeatWait]: '繰り返しまでの待機（分）',
    [UiText.SettingReceiveAllWaitHelp]: '次の一括受け取りまでの待機時間。',
    [UiText.SettingMailWaitHelp]: 'メールボックスが空になるか上限に達した後の待機時間。',
    [UiText.SettingSendWaitHelp]: '次に友だちリストを回るまでの待機時間。',
    [UiText.SettingReceiveOneByOne]: 'ハートを1通ずつ受け取り',
    [UiText.SettingReceiveOneByOneHelp]: 'メールを1通ずつ開き、全員にハートを送り返します。一括受け取りより遅いです。',
    [UiText.SettingSkipRuby]: 'ルビーをスキップ',
    [UiText.SettingSkipRubyHelp]: 'ルビーのギフトをメールボックスに残します。',
    [UiText.SettingSkipMedals]: 'メダルをスキップ',
    [UiText.SettingSkipMedalsHelp]: 'ミッションクリアのメダルをメールボックスに残します。',
    [UiText.SettingClaimAllOldMails]: '古いメールを一括受け取り',
    [UiText.SettingClaimAllOldMailsHelp]: 'コインのメールを1通ずつ受け取り、残りは一括で受け取ります。',
    [UiText.SettingMailOpenMax]: 'メールボックスを開く最大回数',
    [UiText.SettingMailOpenMaxHelp]: '次の作業に移るまで連続で開く回数。空になれば早めに終了します。',
    [UiText.SettingSendHeartsAuto]: 'ハートを自動送信',
    [UiText.SettingSendHeartsAutoHelp]: '友だちリストを順にたどってハートを送ります。',
    [UiText.SettingSendToZeroScore]: 'スコア0にも送る',
    [UiText.SettingSendToZeroScoreHelp]: 'スコアのない友だち（休止中や自動送信の人）にも送ります。',
    [UiText.SettingSendMaxRuntime]: '最大実行時間（分）',
    [UiText.SettingSendMaxRuntimeHelp]: '0 なら毎回1位から送ります。',
    [UiText.SettingAppRestartFrequency]: 'ツムツムの再起動間隔（分）',
    [UiText.SettingAppRestartFrequencyHelp]: '長時間の実行中、この間隔でゲームを再起動します。0 = オフ。自動起動が必要です。',
    [UiText.SettingBuildDate]: 'ビルド日: $BUILD_DATE',
    [UiText.SettingDebugLogs]: 'デバッグログ',
    [UiText.SettingDebugLogsHelp]: 'ログをより詳しく出力します。',
    [UiText.SettingDebugGame]: 'ゲームのデバッグ',
    [UiText.SettingDebugGameHelp]: '判定用のスクリーンショットと各画面の画像を保存します。開発用。',
    [UiText.SettingWalkthrough]: '操作の記録 (walkthrough/)',
    [UiText.SettingWalkthroughHelp]: '自分でゲームを操作すると、画面とタップが記録されます。他は動作しません。',
    [UiText.SettingCollectUnknownScreens]: '未知の画面を収集 (corpus/)',
    [UiText.SettingCollectUnknownScreensHelp]: '認識できない画面を保存します。修正のために送ってください。',
    [UiText.SettingPageHistoryDepth]: '画面履歴の件数',
    [UiText.SettingPageHistoryDepthHelp]: '報告用に覚えておく画面数。ゲームのデバッグ中は各画面の画像も保存します。',
    [UiText.SettingReportIssue]: '問題を報告',
    [UiText.SettingReportIssueHelp]: '画面、最近の画面、ログ、設定を保存します。実行履歴から送信してください。',
    [UiText.ReportNotePlaceholder]: '何が起きましたか？（任意）',
    [UiText.ReportSaved]: '保存しました。アプリの実行履歴から「共有」で送信してください。',
    [UiText.ReportFailed]: '何も保存されませんでした。先にスクリプトを開始してから、もう一度お試しください。',
    [UiText.SettingDetectMyTsum]: 'マイツムを判定',
    [UiText.SettingDetectMyTsumHelp]: 'プレイ開始前の画面から選択中のツムを読み取ります。その画面を開き、スクリプトを止めて「判定」を押してください。',
    [UiText.DetectMyTsumFound]: '{name}（{tsum}）— スコア {score}、差 {margin}。',
    [UiText.DetectMyTsumNearest]: '確かな一致なし。最も近いもの: {name}（{tsum}）— スコア {score}、差 {margin}。',
    [UiText.DetectMyTsumRunUp]: 'スクリプトの実行中は、毎ラウンド前に自動でツムを判定します。ここで試すには停止してください。',
    [UiText.DetectMyTsumNoLibrary]: 'このビルドにはツムのライブラリがありません。',
    [UiText.DetectMyTsumUnreadable]: 'ツムのアイコンを読み取れませんでした。ゲームはプレイ開始前の画面ですか？',
    [UiText.DetectMyTsumFailed]: '何も読み取れませんでした。先にスクリプトを読み込んでから、もう一度お試しください。',

    [UiText.BubbleOneMidChain]: 'チェーン中にボムを1つ',
    [UiText.BubbleAllMidChain]: 'チェーン中にボムを全部',
    [UiText.BubbleSaveOneMidChain]: 'チェーン中にボムを1つ残す',
    [UiText.BubbleSaveOne]: 'ボムを1つ残す',
    [UiText.BubbleAllAsap]: 'ボムをすぐ全部',
    // クイックバーのチップ用。数文字の幅しかない。
    [UiText.BubbleOneMidChainShort]: '途中1つ',
    [UiText.BubbleAllMidChainShort]: '途中全部',
    [UiText.BubbleSaveOneMidChainShort]: '途中1つ残す',
    [UiText.BubbleSaveOneShort]: '1つ残す',
    [UiText.BubbleAllAsapShort]: 'すぐ全部',

    [UiText.ButtonCopy]: 'コピー',
    [UiText.ButtonPaste]: '貼り付け',
    [UiText.ButtonNow]: '今すぐ',
    [UiText.ButtonApply]: '適用',
    [UiText.ButtonClose]: '閉じる',
    [UiText.ButtonSaveFile]: 'ファイルに保存',
    [UiText.ButtonReport]: '報告',
    [UiText.ButtonSaveReport]: '報告を保存',
    [UiText.ButtonDetect]: '判定',
    [UiText.CompanionConfirmSpend]: '見ていない間に GAP がコインを使うようになります。変更しますか？',
    [UiText.CompanionConfirmSpendNow]: 'コインを使います。今すぐ実行しますか？',

    [UiText.ChromeReset]: '設定をリセット',
    [UiText.ChromeRestartNow]: 'ツムツムスクリプトを今すぐ再起動',
    [UiText.ChromeThemeToLight]: 'ライトモードに切り替え',
    [UiText.ChromeThemeToDark]: 'ダークモードに切り替え',
    [UiText.ChromeStyleToFelt]: 'フェルトスタイルに切り替え',
    [UiText.ChromeStyleToAccessible]: 'アクセシブルスタイルに切り替え',
    [UiText.ChromeMoreTabs]: '他のタブを表示',
    [UiText.ChromeCopyCode]: 'コード',
    [UiText.ChromeCopyCodeLabel]: '設定コードをコピー',
    [UiText.ChromeCopied]: 'コピー済み',
    [UiText.ChromeCopyFailed]: '失敗',

    [UiText.ShareCopied]: '設定コードをコピーしました。必要な人に貼り付けて渡してください。',
    [UiText.ShareCopyFailed]: 'クリップボードを使えません。下のコードを手動でコピーしてください。',
    [UiText.SharePasteEmpty]: 'クリップボードに設定コードがありません。下に貼り付けて「適用」をタップしてください。',
    [UiText.SharePastePrompt]: '下に設定コードを貼り付けて「適用」をタップしてください。',
    [UiText.ShareOtherFormat]: 'このコードは別バージョンの形式のため読み込めません。新しくコピーしてもらってください。',
    [UiText.ShareNotACode]: '設定コードではありません。',
    [UiText.ShareListingOn]: 'オン',
    [UiText.ShareListingOff]: 'オフ',
    [UiText.ShareApplied]: '{applied} 件の設定を適用しました{from}。',
    [UiText.ShareAppliedSkipped]: '{applied} 件の設定を適用し、{skipped} 件をスキップしました{from}。',

    [UiText.PresetNone]: 'プリセットなし',
    [UiText.PresetOpen]: 'プリセットを切り替え',
    [UiText.PresetManage]: 'プリセットを保存',
    [UiText.PresetNameHint]: 'プリセット名',
    [UiText.PresetSaveNew]: '新規保存',
    [UiText.PresetUpdate]: '上書き',
    [UiText.PresetDelete]: '削除',
    [UiText.PresetSaved]: '{name} を保存しました。',
    [UiText.PresetUpdated]: '{name} を上書きしました。',
    [UiText.PresetDeleted]: '{name} を削除しました。',
    [UiText.PresetNeedsName]: '先にプリセット名を入力してください。',
    [UiText.PresetNameTaken]: '{name} は保存済みです — 「上書き」で置き換えます。',
    [UiText.PresetUnknownName]: '{name} というプリセットはありません。',
    [UiText.PresetFull]: 'これ以上プリセットを追加できません（上限 {max}）。',
    [UiText.PresetStoreFailed]: 'このデバイスにはプリセットを保存できませんでした。',
    [UiText.PresetExportNone]: '書き出すプリセットがまだありません。',
    [UiText.PresetExportCopied]: 'すべてのプリセットをクリップボードにコピーしました。',
    [UiText.PresetExportCopyFailed]: 'クリップボードを使えません — テキストを選択したので、手動でコピーしてください。',
    [UiText.PresetExportSaved]: '{path} に書き出しました。',
    [UiText.PresetExportNoEngine]: '先に一度「再生」を押してください。ファイルはこのページではなくスクリプトが書き出します。',
    [UiText.PresetExportFailed]: 'ファイルを書き出せませんでした: {error}',

    [UiText.LogNoSettings]: '設定が見つからないため、デフォルトを使用します',
    [UiText.LogLoadSettings]: '設定を読み込み',
    [UiText.LogSaveSettings]: '設定を保存',
    [UiText.LogStartCommand]: '開始コマンド',

    [UiText.RunEvery]: '{amount}ごと',
    [UiText.RunHours]: '{count} 時間',
    [UiText.RunMinutes]: '{count} 分',
    [UiText.RunSeconds]: '{count} 秒',
    [UiText.RunWalkthrough]: '操作を記録',
    [UiText.RunWalkthroughDetail]: 'あなたの操作を見て記録します。他の作業は登録されません。',
    [UiText.RunMailbox]: 'メールボックスを1通ずつ開く',
    [UiText.RunMailboxDetail]: '1回あたり最大 {max} 通。',
    [UiText.RunReceiveAll]: 'ハートを一括受け取り',
    [UiText.RunSendHearts]: 'ハートを送る',
    [UiText.RunSendHeartsLimited]: '{minutes} 分で停止し、次回はその続きから送ります。',
    [UiText.RunSendHeartsUnlimited]: '時間制限なし。毎回1位から全員に送ります。',
    [UiText.RunRestartApp]: 'ツムツムを再起動',
    [UiText.RunRestartAppDetail]: '初回は開始直後ではなく、1周期後です。',
    [UiText.RunClickAssist]: 'クリックアシスト',
    [UiText.RunClickAssistDetail]: '自動プレイの代わりに、選んだツムをスクリプトがつなぎます。',
    [UiText.RunUnlockLevel]: 'レベル上限を解放',
    [UiText.RunBuyBoxes]: 'BOXを購入',
    [UiText.RunBuyBoxesDetail]: '{box}、{size}、最大 {max} 回購入。売り切れかコイン不足で停止し、ルビーは使いません。',
    [UiText.RunPlayRound]: 'ラウンドをプレイ',
    [UiText.RunPlayRoundDelay]: 'ラウンド間に {minutes} 分待機。',
    [UiText.RunPlayRoundCap]: '{minutes} 分を超えたラウンドは諦めます: {action}。',
    [UiText.RunPlayRoundStopAfter]: '{games} ゲーム後: {action}。',
    [UiText.RunItemsNone]: 'ボーナスアイテムなし。',
    [UiText.RunItemsSome]: '各ラウンド前にセットするアイテム: {items}。',
    [UiText.RunItemsSeparator]: '、',
    [UiText.RunNoteRecording]: '記録モード: 画面上の操作はすべてあなたが行います。',
    [UiText.RunNoteNothingPlays]: 'プレイしません: 自動プレイとクリックアシストがどちらもオフです。',
    [UiText.RunNoteOrder]: '開始時点ではすべてが実行対象なので、この順序で実行されます。その後はそれぞれの間隔で'
        + '繰り返し、同時に対象になったときはこのリストで上にあるものが先です。ラウンドは必ず最後まで'
        + 'プレイするため、途中で対象になった作業は終了を待ちます。同じ作業で5回連続エラーが出ると'
        + 'ゲームアプリを再起動します。',
    [UiText.RunFlowTitle]: 'ラウンド中、盤面スキャンごとに:',

    [UiText.FlowScan]: '盤面をスキャン',
    [UiText.FlowPopAll]: 'ボムをすべて割る',
    [UiText.FlowPopAllButOne]: 'ボムを1つ残して割る',
    [UiText.FlowPlan]: 'チェーンを計画（最長 {max}、距離 {reach}%）',
    [UiText.FlowMyTsumFirst]: 'マイツム優先',
    [UiText.FlowKeep]: '上位 {count} 本を採用',
    [UiText.FlowTapSkill]: 'ゲージが満タンならスキルをタップ',
    [UiText.FlowHoldBubblesFever]: 'フィーバー最後の {sec} 秒はボムを残す',
    [UiText.FlowLinkOneBubble]: 'つなぐ（チェーン中にボムを1つ）',
    [UiText.FlowLinkAllButOne]: 'つなぐ（チェーン中にボムを1つ残して割る）',
    [UiText.FlowLinkAllBubbles]: 'つなぐ（チェーン中にボムを全部）',
    [UiText.FlowLink]: 'つなぐ',
    [UiText.FlowFan]: '4スキャンごとにファン',
    [UiText.FlowNoSkill]: 'スキルなし',
    [UiText.FlowSettleSkill]: '盤面が埋まるまで最大 {sec} 秒待つ',
    [UiText.FlowUseSkill]: 'スキルを使う: {skill} Lv{level}',
    [UiText.FlowLorcanaCard]: 'Lorcana カードが出たらタップ',
    [UiText.FlowBoardUp]: '盤面はまだ表示中？',
} satisfies UiStringsPartial);
