// Traditional Chinese (Taiwan).
//
// `UiStringsPartial`, so it may be incomplete: anything not here falls back to
// English at runtime, which is what lets a new string ship before it has been
// translated. `npm run i18n:check` lists what is still missing.
//
// Missing on purpose right now: the Quick Bar strip (`qb.*`) and the box
// dropdown's option labels (`box.*`), which name the store's tabs and are read
// off the game's own English wording. The rule this project already follows for
// log sentences applies here too -- an untranslated English label is better than
// an invented translation. The keys exist, so translating them is one edit here.

i18nRegister(Locale.Taiwan, '中文', {
    [UiText.TabGeneral]: '一般',
    [UiText.TabGameplay]: '遊戲',
    // Was `GroupChores`, the Gameplay tab's Chores card, before the chores got a
    // tab of their own. Same English string, same translation -- carried across
    // rather than dropped, so the tab is not the one untranslated word in the bar.
    [UiText.TabChores]: '雜項',
    [UiText.TabSkills]: '技能',
    [UiText.TabRound]: '對局',
    [UiText.TabHearts]: '愛心',
    [UiText.TabDebug]: '除錯',

    [UiText.GroupDevice]: '裝置',
    [UiText.GroupRunOrder]: '執行順序',
    [UiText.GroupRunOrderHelp]: '依目前設定，腳本會依序做的事。',
    [UiText.GroupSettingsCode]: '設定碼',
    [UiText.GroupSettingsCodeHelp]: '把玩法設定複製成一行文字，或貼上別人的。',
    [UiText.GroupRun]: '執行',
    [UiText.GroupChains]: '連鎖',
    [UiText.GroupLinking]: '連線',
    [UiText.GroupBoardHelpers]: '版面輔助',
    [UiText.GroupItems]: '道具',
    [UiText.GroupItemsHelp]: '開局前購買，每一局都會花金幣。',
    [UiText.GroupLevelCaps]: '等級上限',
    [UiText.GroupBoxes]: 'BOX',
    [UiText.GroupBoxesHelp]: '每局之間到商店購買。絕不花紅寶石。',
    [UiText.GroupSkill]: '技能',
    [UiText.GroupTiming]: '時機',
    [UiText.GroupReceiveAll]: '收全部愛心',
    [UiText.GroupMailbox]: '一顆一顆收愛心',
    [UiText.GroupSendHearts]: '送愛心',
    [UiText.GroupExperimental]: '實驗性功能',
    [UiText.GroupExperimentalHelp]: '不保證每種情況都正常。',
    [UiText.GroupDiagnostics]: '診斷',

    [UiText.SettingLanguage]: '語言',
    [UiText.SettingLanguageHelp]: '本頁與快捷列的語言。',
    [UiText.SettingSpecialScreenRatio]: '特殊螢幕比例(長螢幕)(遊戲中啟動)',
    [UiText.SettingSpecialScreenRatioHelp]: '適用上下黑邊不對稱的長螢幕。請先自己開遊戲，不能搭配自動開啟。',
    [UiText.SettingDeviceFps]: '裝置畫面更新率',
    [UiText.SettingDeviceFpsHelp]: '影響自動消失畫面的持續時間。',
    [UiText.SettingAutoLaunchApp]: '自動開啟 Tsum App',
    [UiText.SettingAutoLaunchAppHelp]: '腳本啟動時開啟 Tsum Tsum。開特殊螢幕比例時請關閉。',
    [UiText.SettingShareSettings]: '分享設定',
    [UiText.SettingShareListing]: '複製時附上設定清單',
    [UiText.SettingShareListingHelp]: '附上技能類型，以及改過預設值的設定。',
    [UiText.SettingExportPresets]: '匯出組合',
    [UiText.SettingExportPresetsHelp]: '每個組合一組設定碼，貼回上面即可還原組合。',
    [UiText.SettingAutoPlayGame]: '自動玩遊戲',
    [UiText.SettingAutoPlayGameHelp]: '沒有其他工作時就玩一局。關閉則只做雜項。',
    [UiText.SettingClickAssist]: '點擊輔助（點選即連線）',
    [UiText.SettingClickAssistHelp]: '取代自動遊玩：由你選擇 Tsum，腳本負責連線。',
    [UiText.SettingRoundDelay]: '每局之間休息(分)',
    [UiText.SettingRoundDelayHelp]: '0 表示不休息。「立即」可結束正在進行的休息。',
    [UiText.SettingMaxRound]: '單局時間上限(分)',
    [UiText.SettingMaxRoundHelp]: '超過這個時間就放棄這一局。0 表示不限制。',
    [UiText.SettingMaxRoundAction]: '超過時間上限時',
    [UiText.SettingMaxRoundActionHelp]: '單局時間上限到了要做什麼。',
    [UiText.MaxRoundCoast]: '停止操作，等本局時間結束',
    [UiText.MaxRoundStop]: '停止腳本',
    [UiText.SettingStopAfterGames]: '玩幾局後停止',
    [UiText.SettingStopAfterGamesHelp]: '玩完這麼多局後執行下方動作。0 表示不停止。',
    [UiText.SettingStopAfterAction]: '玩完局數後',
    [UiText.SettingStopAfterActionHelp]: '達到局數後要做什麼。',
    [UiText.StopAfterAutoPlayOff]: '關閉自動玩遊戲',
    [UiText.StopAfterPause]: '暫停腳本',
    [UiText.StopAfterStop]: '停止腳本',
    [UiText.StopAfterAutoPlayOffShort]: '關自動',
    [UiText.StopAfterPauseShort]: '暫停',
    [UiText.StopAfterStopShort]: '停止',
    [UiText.SettingMaxChainsPerScan]: '每次掃描連線數',
    [UiText.SettingMaxChainsPerScanHelp]: '重新掃描前連幾條線。少較準，多較快。',
    [UiText.SettingMaxChain]: '最大連鎖數',
    [UiText.SettingMaxChainHelp]: '最長連線長度。設低適合靠連線次數得分的 Tsum。',
    [UiText.SettingLinkReach]: '連線距離（Tsum寬度百分比）',
    [UiText.SettingLinkReachHelp]: '可連線的最大距離。太小連不長，太大遊戲不接受拖曳。',
    [UiText.SettingPrioritizeMyTsum]: '優先連結我的Tsum',
    [UiText.SettingPrioritizeMyTsumHelp]: '技能集氣較快。',
    [UiText.SettingTrackRoundStats]: '記錄每局數據',
    [UiText.SettingTrackRoundStatsHelp]: '每天 (UTC) 一個 CSV，存於 stats/：stats_YYYYMMDD.csv。',
    [UiText.SettingShareRoundStats]: '分享每局數據',
    [UiText.SettingShareRoundStatsHelp]: '約每分鐘將新的資料列傳送到統計伺服器。需要開啟「記錄每局數據」，並在 GAP 中設定統計伺服器且允許網路存取（資料庫 > 此腳本 > 設定）。',
    [UiText.SettingBubbleStrategy]: '泡泡策略',
    [UiText.SettingBubbleStrategyHelp]: '連線中戳破的泡泡消得更多，預設會留給連線。',
    [UiText.SettingHoldBubblesLastFever]: 'Fever尾段保留泡泡秒數',
    [UiText.SettingHoldBubblesLastFeverHelp]: 'Fever 最後幾秒不戳泡泡，留到結束後集氣。0 表示關閉。',
    [UiText.SettingUseFan]: '使用風扇',
    [UiText.SettingUseFanHelp]: '每隔幾次掃描用風扇搧一下版面。',
    [UiText.SettingBonusScore]: '道具Score',
    [UiText.SettingBonusScoreHelp]: '這一局的分數加成。',
    [UiText.SettingBonusCoin]: '道具Coin',
    [UiText.SettingBonusCoinHelp]: '這一局拿到比較多金幣。',
    [UiText.SettingBonusExp]: '道具Exp',
    [UiText.SettingBonusExpHelp]: '這一局拿到比較多經驗值。',
    [UiText.SettingBonusTime]: '道具Time',
    [UiText.SettingBonusTimeHelp]: '遊玩時間多幾秒。',
    [UiText.SettingBonusBubble]: '道具Bubble',
    [UiText.SettingBonusBubbleHelp]: '版面上的泡泡變多。',
    [UiText.SettingBonus5to4]: '道具五變四',
    [UiText.SettingBonus5to4Help]: '少一種 Tsum，比較容易連線。',
    [UiText.SettingBonusCombo]: '道具Combo',
    [UiText.SettingBonusComboHelp]: '維持 Combo 的時間變長。',
    [UiText.SettingUnlockLevel]: '解鎖角色等級時間(時)',
    [UiText.SettingUnlockLevelHelp]: '間隔時數，0 表示關閉。「立即」會馬上跑一次。',
    [UiText.SettingUnlockMyTsumLevel]: '自動解鎖 MyTsum 等級上限',
    [UiText.SettingUnlockMyTsumLevelHelp]: '一局結束時 MyTsum 等級到上限，就解鎖一次（消耗金幣）。',
    [UiText.SettingBuyBox]: '購買BOX時間(時)',
    [UiText.SettingBuyBoxHelp]: '間隔時數，0 表示關閉。買到售完或金幣不足。「立即」會馬上跑一次。',
    [UiText.SettingBuyBoxType]: '要買的BOX',
    [UiText.SettingBuyBoxTypeHelp]: '只買這一種。Select Box 與 Pick-Up Capsule 共用限定位置。',
    [UiText.SettingBuyBoxSize]: '每次購買數量',
    [UiText.SettingBuyBoxSizeHelp]: '商店拒絕十連時，「十連」就停，「先十連再單抽」改單抽買完。',
    [UiText.BoxSizeOne]: '一次買一個',
    [UiText.BoxSizeTen]: '一次買十連',
    [UiText.BoxSizeTenThenOne]: '先十連，再單抽到售完',
    [UiText.SettingBuyBoxMax]: '每次購買次數上限',
    [UiText.SettingBuyBoxMaxHelp]: '每次的安全上限。十連抽算一次。',
    [UiText.SettingSkillType]: '技能類型',
    [UiText.SettingSkillTypeHelp]: '消除系適用大多數 Tsum；有名字的選項為該 Tsum 調校。',
    [UiText.SettingSkillLevel]: '技能等級',
    [UiText.SettingSkillLevelHelp]: '只有仙度瑞拉、光年隊長與加冕日艾莎會用到。',
    [UiText.SettingSkillWaitingTime]: '技能等待時間(秒)',
    [UiText.SettingSkillWaitingTimeHelp]: '發動後最多靜置這麼久；Tsum 落定就繼續玩。',
    [UiText.SettingSkillSettle]: '等待版面補滿(秒)',
    [UiText.SettingSkillSettleHelp]: '發動前最多等這麼久讓版面補滿。0 表示馬上放。',
    [UiText.SettingSkillReactivation]: '技能再次發動延遲(秒)',
    [UiText.SettingSkillReactivationHelp]: '發動後這段時間內先不再放，避免重啟還在進行的技能。0 表示關閉。',
    [UiText.SettingNoSkillLastFever]: 'Fever尾段扣技能秒數',
    [UiText.SettingNoSkillLastFeverHelp]: 'Fever 快結束時先不放技能，留著開下一次。0 表示關閉。',
    [UiText.SettingSkillAutoTap]: '自動點擊技能',
    [UiText.SettingSkillAutoTapHelp]: '集氣一滿就放，連線途中也放。',
    [UiText.SettingLorcanaCard]: 'Lorcana 卡片',
    [UiText.SettingLorcanaCardHelp]: '點擊變身卡片，並清掉墨石。',
    [UiText.SettingReceiveAllHearts]: '收全部愛心',
    [UiText.SettingReceiveAllHeartsHelp]: '按一次「全部領取」。快，但不回送愛心。',
    [UiText.SettingRepeatWait]: '完成後休息時間(分)',
    [UiText.SettingReceiveAllWaitHelp]: '下一次「全部領取」前要等多久。',
    [UiText.SettingMailWaitHelp]: '信箱清空或達到上限後，隔多久再開。',
    [UiText.SettingSendWaitHelp]: '下一輪送愛心前要等多久。',
    [UiText.SettingReceiveOneByOne]: '一顆一顆收愛心',
    [UiText.SettingReceiveOneByOneHelp]: '逐一開信並回送愛心給每個人。比「全部領取」慢。',
    [UiText.SettingSkipRuby]: '跳過紅寶石',
    [UiText.SettingSkipRubyHelp]: '紅寶石禮物留在信箱。',
    [UiText.SettingSkipMedals]: '跳過獎章',
    [UiText.SettingSkipMedalsHelp]: '任務獎章留在信箱。',
    [UiText.SettingClaimAllOldMails]: '領取過期郵件',
    [UiText.SettingClaimAllOldMailsHelp]: '先逐一領金幣信，其餘用「全部領取」。',
    [UiText.SettingMailOpenMax]: '重複檢查上限次數',
    [UiText.SettingMailOpenMaxHelp]: '換下一項工作前最多連開幾次信箱；空了就停。',
    [UiText.SettingSendHeartsAuto]: '自動送愛心',
    [UiText.SettingSendHeartsAutoHelp]: '照好友清單一路往下送愛心。',
    [UiText.SettingSendToZeroScore]: '送心給 0 分',
    [UiText.SettingSendToZeroScoreHelp]: '也送給沒有分數的好友（不玩或自動送心的人）。',
    [UiText.SettingSendMaxRuntime]: '執行時間上限(分)',
    [UiText.SettingSendMaxRuntimeHelp]: '0 將從第一名開始送。',
    [UiText.SettingAppRestartFrequency]: '定時重啟Tsum app（分）',
    [UiText.SettingAppRestartFrequencyHelp]: '長時間執行時每隔這麼久重開遊戲。0 表示關閉；需開啟自動開啟。',
    [UiText.SettingBuildDate]: '建造日期: $BUILD_DATE',
    [UiText.SettingDebugLogs]: '调试日志',
    [UiText.SettingDebugLogsHelp]: '日誌記錄更詳細的內容。',
    [UiText.SettingDebugGame]: '调试游戏',
    [UiText.SettingDebugGameHelp]: '存下判讀用截圖與每個畫面的截圖。供開發使用。',
    [UiText.SettingWalkthrough]: '導覽紀錄 (walkthrough/)',
    [UiText.SettingWalkthroughHelp]: '自己操作遊戲，腳本記錄每個畫面與點擊。其他功能停用。',
    [UiText.SettingCollectUnknownScreens]: '收集無法辨識的畫面 (corpus/)',
    [UiText.SettingCollectUnknownScreensHelp]: '存下無法辨識的畫面，可回傳做修正。',
    [UiText.SettingPageHistoryDepth]: '畫面紀錄depth',
    [UiText.SettingPageHistoryDepthHelp]: '記住的畫面數，問題回報會附上。調試遊戲會每個都存圖。',
    [UiText.SettingReportIssue]: '回報問題',
    [UiText.SettingReportIssueHelp]: '把畫面、近期紀錄與設定存下，再從執行紀錄分享送出。',
    [UiText.ReportNotePlaceholder]: '發生什麼問題？（可略）',
    [UiText.ReportSaved]: '已儲存。請用 App 執行紀錄裡的分享送出。',
    [UiText.ReportFailed]: '沒有存下任何東西。請先啟動腳本再試一次。',
    [UiText.SettingDetectMyTsum]: '辨識 MyTsum',
    [UiText.SettingDetectMyTsumHelp]: '從開局畫面讀取選用的 Tsum。開到該畫面、停止腳本，再按辨識。',
    [UiText.DetectMyTsumFound]: '{name}（{tsum}）— 分數 {score}，差距 {margin}。',
    [UiText.DetectMyTsumNearest]: '沒有可信的結果。最接近：{name}（{tsum}）— 分數 {score}，差距 {margin}。',
    [UiText.DetectMyTsumRunUp]: '腳本執行中，每局開始前會自己辨識 Tsum。請先停止腳本再測試。',
    [UiText.DetectMyTsumNoLibrary]: '這個版本沒有 Tsum 樣板。',
    [UiText.DetectMyTsumUnreadable]: '無法讀取 Tsum 圖示。遊戲在開始畫面嗎？',
    [UiText.DetectMyTsumFailed]: '沒有讀到任何東西。請先載入腳本再試一次。',

    [UiText.BubbleOneMidChain]: '連線時戳一顆',
    [UiText.BubbleAllMidChain]: '連線時全戳',
    [UiText.BubbleSaveOneMidChain]: '連線時留一顆',
    [UiText.BubbleSaveOne]: '保留一顆',
    [UiText.BubbleAllAsap]: '盡快全戳',
    // 快捷列的短名：晶片只有幾個字的寬度。
    [UiText.BubbleOneMidChainShort]: '連線一顆',
    [UiText.BubbleAllMidChainShort]: '連線全戳',
    [UiText.BubbleSaveOneMidChainShort]: '連線留一顆',
    [UiText.BubbleSaveOneShort]: '留一顆',
    [UiText.BubbleAllAsapShort]: '盡快全戳',

    // [UiText.SkillGroupBurst]: '消除系',
    // [UiText.SkillGroupBubble]: '泡泡系',
    // [UiText.SkillGroupUnique]: '特殊系',

    // [UiText.StatusFlagAlpha]: 'ALPHA',
    // [UiText.StatusFlagBeta]: 'BETA',

    // [UiText.SkillBurst]: '消除系',
    // [UiText.SkillBurstBubbles]: '消除系＋清泡泡',
    // [UiText.SkillDonald]: '唐老鴨',
    // [UiText.SkillHolidayDonald]: '假日唐老鴨',
    // [UiText.SkillJediLuke]: '絕地路克',
    // [UiText.SkillMoana]: '莫娜',
    // [UiText.SkillMarie]: '瑪麗',
    // [UiText.SkillMissBunny]: '小兔子',
    // [UiText.SkillRabbit]: '兔子',
    // [UiText.SkillHornHatMickey]: '角帽米奇',
    // [UiText.SkillSnowWhite]: '白雪公主',
    // [UiText.SkillCinderella]: '仙度瑞拉',
    // [UiText.SkillSheriffWoody]: '警長胡迪',
    // [UiText.SkillCabbageMickey]: '高麗菜米奇',
    // [UiText.SkillCptLightyear]: '光年隊長',
    // [UiText.SkillCptLightyear120]: '光年隊長 120',
    // [UiText.SkillLightningMcQueenPlus]: '閃電麥坤+',
    // [UiText.SkillFormalBeast]: '禮服野獸',
    // [UiText.SkillGaston]: '加斯頓',
    // [UiText.SkillTiaraMinniePlus]: '皇冠米妮+',
    // [UiText.SkillCoronationElsa]: '加冕日艾莎',
    // [UiText.SkillRapunzelPlus]: '樂佩+',
    // [UiText.SkillLorcanaAurora]: 'Lorcana 奧蘿拉',
    // [UiText.SkillPairTsum]: '搭檔Tsum',
    // [UiText.SkillNoSkill]: '没有技能',

    [UiText.ButtonCopy]: '複製',
    [UiText.ButtonPaste]: '貼上',
    [UiText.ButtonNow]: '立即',
    [UiText.ButtonApply]: '套用',
    [UiText.ButtonClose]: '關閉',
    [UiText.ButtonSaveFile]: '存成檔案',
    [UiText.ButtonReport]: '回報',
    [UiText.ButtonSaveReport]: '儲存回報',
    [UiText.ButtonDetect]: '辨識',
    [UiText.CompanionConfirmSpend]: '這會讓 GAP 在你沒看著時花費金幣。要變更嗎？',
    [UiText.CompanionConfirmSpendNow]: '這會花費金幣。要立即執行嗎？',

    [UiText.ChromeReset]: '重設設定',
    [UiText.ChromeRestartNow]: '立即重启TsumTsum脚本',
    [UiText.ChromeThemeToLight]: '切換為淺色模式',
    [UiText.ChromeThemeToDark]: '切換為深色模式',
    [UiText.ChromeAppearance]: '外觀',
    [UiText.ChromeAppearanceClose]: '關閉',
    [UiText.ChromeStyle]: '風格',
    [UiText.ChromeStyleAccessible]: '無障礙',
    [UiText.ChromeStyleFelt]: '毛氈',
    [UiText.ChromeTheme]: '主題',
    [UiText.ChromeThemeDark]: '深色',
    [UiText.ChromeThemeLight]: '淺色',
    [UiText.ChromeThemeDevice]: '跟隨裝置',
    [UiText.ChromeSize]: '大小',
    [UiText.ChromeSizeXs]: '特小',
    [UiText.ChromeSizeS]: '小',
    [UiText.ChromeSizeM]: '中',
    [UiText.ChromeSizeL]: '大',
    [UiText.ChromeSizeFeltNote]: '大小僅適用於無障礙風格。',
    [UiText.ChromeMoreTabs]: '顯示更多分頁',
    [UiText.ChromeCopyCode]: '代碼',
    [UiText.ChromeCopyCodeLabel]: '複製設定碼',
    [UiText.ChromeCopied]: '已複製',
    [UiText.ChromeCopyFailed]: '失敗',

    [UiText.ShareCopied]: '設定碼已複製，貼給別人即可。',
    [UiText.ShareCopyFailed]: '無法存取剪貼簿，請手動複製下方的設定碼。',
    [UiText.SharePasteEmpty]: '剪貼簿裡沒有設定碼，請把設定碼貼到下方再按套用。',
    [UiText.SharePastePrompt]: '請把設定碼貼到下方，再按套用。',
    [UiText.ShareOtherFormat]: '這個設定碼來自其他版本的格式，這個版本讀不了。請對方重新複製一份。',
    [UiText.ShareNotACode]: '這不是有效的設定碼。',
    [UiText.ShareListingOn]: '開',
    [UiText.ShareListingOff]: '關',
    [UiText.ShareApplied]: '已套用 {applied} 項設定{from}。',
    [UiText.ShareAppliedSkipped]: '已套用 {applied} 項設定{from}，略過 {skipped} 項。',

    [UiText.PresetNone]: '未使用組合',
    [UiText.PresetOpen]: '切換組合',
    [UiText.PresetManage]: '儲存組合',
    [UiText.PresetNameHint]: '組合名稱',
    [UiText.PresetSaveNew]: '另存新組合',
    [UiText.PresetUpdate]: '覆寫',
    [UiText.PresetDelete]: '刪除',
    [UiText.PresetSaved]: '已儲存 {name}。',
    [UiText.PresetUpdated]: '已覆寫 {name}。',
    [UiText.PresetDeleted]: '已刪除 {name}。',
    [UiText.PresetNeedsName]: '請先為組合命名。',
    [UiText.PresetNameTaken]: '{name} 已經存在 — 用「覆寫」取代它。',
    [UiText.PresetUnknownName]: '沒有名為 {name} 的組合。',
    [UiText.PresetFull]: '組合數量已達上限 {max}。',
    [UiText.PresetStoreFailed]: '這台裝置無法儲存組合。',
    [UiText.PresetExportNone]: '目前還沒有組合可以匯出。',
    [UiText.PresetExportCopied]: '已複製所有組合到剪貼簿。',
    [UiText.PresetExportCopyFailed]: '剪貼簿無法使用 — 文字已選取，請手動複製。',
    [UiText.PresetExportSaved]: '已寫入 {path}。',
    [UiText.PresetExportNoEngine]: '請先按一次「播放」：檔案是由腳本寫入，不是這個頁面。',
    [UiText.PresetExportFailed]: '無法寫入檔案：{error}',
    [UiText.PresetImported]: '已儲存組合：{names}。',

    [UiText.LogNoSettings]: '没有找到设置，使用默认设置',
    [UiText.LogLoadSettings]: '讀取設定',
    [UiText.LogSaveSettings]: '儲存設定',
    [UiText.LogStartCommand]: '啟動命令',

    [UiText.RunEvery]: '每 {amount}',
    [UiText.RunHours]: '{count} 小時',
    [UiText.RunMinutes]: '{count} 分',
    [UiText.RunSeconds]: '{count} 秒',
    [UiText.RunWalkthrough]: '記錄你的操作',
    [UiText.RunWalkthroughDetail]: '只記錄你的操作，其他工作一個都不會註冊。',
    [UiText.RunMailbox]: '逐一收取信箱愛心',
    [UiText.RunMailboxDetail]: '每次最多開 {max} 封信。',
    [UiText.RunReceiveAll]: '一次收取全部愛心',
    [UiText.RunSendHearts]: '送出愛心',
    [UiText.RunSendHeartsLimited]: '跑滿 {minutes} 分鐘就停，下次從那裡接著送。',
    [UiText.RunSendHeartsUnlimited]: '沒有時間上限，每次都從第一名開始送整輪。',
    [UiText.RunRestartApp]: '重啟 Tsum App',
    [UiText.RunRestartAppDetail]: '第一次是啟動後一個完整週期，不是馬上。',
    [UiText.RunClickAssist]: '點擊輔助',
    [UiText.RunClickAssistDetail]: '取代自動遊玩：由你選 Tsum，腳本連線。',
    [UiText.RunUnlockLevel]: '解鎖角色等級',
    [UiText.RunBuyBoxes]: '購買BOX',
    [UiText.RunBuyBoxesDetail]: '{box}，{size}，最多買 {max} 次。售完或金幣不足就停；絕不花紅寶石。',
    [UiText.RunPlayRound]: '玩一局',
    [UiText.RunPlayRoundDelay]: '每局之間休息 {minutes} 分鐘。',
    [UiText.RunPlayRoundCap]: '單局超過 {minutes} 分鐘就放棄：{action}。',
    [UiText.RunPlayRoundStopAfter]: '玩完 {games} 局後：{action}。',
    [UiText.RunItemsNone]: '開局前不加道具。',
    [UiText.RunItemsSome]: '開局前選道具：{items}。',
    [UiText.RunItemsSeparator]: '、',
    [UiText.RunNoteRecording]: '錄製模式：畫面上的一切都由你操作。',
    [UiText.RunNoteNothingPlays]: '沒有東西會玩遊戲：自動玩遊戲與點擊輔助都是關的。',
    [UiText.RunNoteOrder]: '啟動時全部都到期，所以會照這個順序跑；之後各自照自己的間隔重複，'
        + '同時到期時排在上面的先跑。一局一定會玩完，中途到期的工作要等這局結束。'
        + '同一項工作連續出錯五次會重啟遊戲 App。',
    [UiText.RunFlowTitle]: '一局進行中，每次掃描版面：',

    [UiText.FlowScan]: '掃描版面',
    [UiText.FlowPopAll]: '戳破所有泡泡',
    [UiText.FlowPopAllButOne]: '留一顆，其餘戳破',
    [UiText.FlowPlan]: '規劃連線（最長 {max} 顆・距離 {reach}%）',
    [UiText.FlowMyTsumFirst]: '我的 Tsum 優先',
    [UiText.FlowKeep]: '取前 {count} 條',
    [UiText.FlowTapSkill]: '技能滿了就點',
    [UiText.FlowHoldBubblesFever]: 'Fever 最後 {sec} 秒保留泡泡',
    [UiText.FlowLinkOneBubble]: '連線（順手戳一顆泡泡）',
    [UiText.FlowLinkAllButOne]: '連線（順手戳到只剩一顆泡泡）',
    [UiText.FlowLinkAllBubbles]: '連線（順手戳掉泡泡）',
    [UiText.FlowLink]: '連線',
    [UiText.FlowFan]: '每 4 次搧風',
    [UiText.FlowNoSkill]: '不使用技能',
    [UiText.FlowSettleSkill]: '最多等 {sec} 秒讓版面補滿',
    [UiText.FlowUseSkill]: '使用技能：{skill} Lv{level}',
    [UiText.FlowLorcanaCard]: '若出現 Lorcana 卡片就點擊',
    [UiText.FlowBoardUp]: '版面還在嗎？',
} satisfies UiStringsPartial);
